[phases.setup]
nixPkgs = ["ffmpeg", "nodejs_22"]

[variables]
LLM_PROVIDER = "groq"

[phases.install]
cmds = ["pnpm install --no-frozen-lockfile"]

[phases.build]
cmds = ["pnpm run build", "cp -r drizzle dist/drizzle", "chmod +x start.sh worker-start.sh"]

[start]
cmd = "sh start.sh"
