/**
 * ClipAnnotation — the full editorial profile of one archive asset.
 * Stored as JSON in media_archive_assets.annotationJson.
 * Version-stamped so a schema change triggers re-annotation.
 *
 * v1: initial fields
 * v2: searchAliases, knowledgeGraphEntities, editorialDescription,
 *     qualityFlags, per-field confidence, extended editorial scores,
 *     facetEmbeddingKeys
 */

// ─── Quality flags ────────────────────────────────────────────────────────────

/**
 * Automatic quality-control flags set by the Archive Intelligence Pipeline.
 * A clip with multiple flags should get a significantly lower editorial score.
 */
export type ClipQualityFlags = {
  /** Frame is predominantly black (dead frame, missing signal). */
  isBlack?: boolean;
  /** Image is blurry beyond usability. */
  isBlurry?: boolean;
  /** Visible watermark or broadcast bug detected. */
  hasWatermark?: boolean;
  /** Clip appears to be a channel/show introduction sequence. */
  isIntroOrOutro?: boolean;
  /** Clip contains rolling credits or end titles. */
  isCreditSequence?: boolean;
  /** Clip is dominated by an on-screen title card or slate. */
  hasTitleCard?: boolean;
  /** Clip is near-identical to another asset (assetId of original). */
  nearDuplicateOf?: number | null;
  /** Clip is a test pattern, colour bars, or technical leader. */
  isTestPattern?: boolean;
};

// ─── Per-field confidence ─────────────────────────────────────────────────────

/** 0–1 confidence per annotation domain. */
export type AnnotationConfidence = {
  persons: number;
  location: number;
  historicalContext: number;
  objects: number;
  emotion: number;
};

// ─── Extended editorial scores ────────────────────────────────────────────────

/** v2 additions to the editorial score block. */
export type ExtendedEditorialScores = {
  /** How significant is this clip for news/current events reporting? */
  newsValue: number;
  /** How well suited is this clip for long-form documentary use? */
  documentaryValue: number;
  /** 0–100 trust score derived from source provenance. */
  sourceQualityScore: number;
  /** How easily can this clip be repurposed for different productions? */
  reusabilityScore: number;
};

// ─── Facet embedding keys ─────────────────────────────────────────────────────

/**
 * Storage keys for per-facet text embeddings generated during ingestion.
 * Each key points to a JSON file in the archive-clip-embeddings directory.
 * Enables facet-specific semantic retrieval (search by persons only, etc.).
 */
export type FacetEmbeddingKeys = {
  /** Full editorial description embedding. */
  description?: string;
  /** Persons-only embedding. */
  persons?: string;
  /** Location-only embedding. */
  location?: string;
  /** Objects-only embedding. */
  objects?: string;
  /** Historical context / events embedding. */
  events?: string;
  /** Emotion / atmosphere embedding. */
  emotions?: string;
  /** Camera style / cinematography embedding. */
  style?: string;
};

// ─── Timeline segment ─────────────────────────────────────────────────────────

/**
 * One temporal segment within a clip.
 * A clip of 8 s may contain 3–5 distinct visual moments.
 * Generated by the v3 multi-frame vision analysis.
 */
export type ClipSegment = {
  /** Segment start time in seconds from clip start. */
  startSec: number;
  /** Segment end time in seconds. */
  endSec: number;
  /** Shot type for this segment: wide | medium | close-up | etc. */
  shotType: string;
  /** One-sentence visual description of what happens in this segment. */
  description: string;
  /** Named persons visible in this segment. */
  persons?: string[];
  /** Key objects visible in this segment. */
  objects?: string[];
  /** Dominant emotion in this segment. */
  emotion?: string;
  /** Camera movement in this segment: static | pan | tilt | zoom | etc. */
  cameraMovement?: string;
  /** Any OCR text detected in this segment. */
  ocrText?: string;
  /** Storage key for segment-level embedding (set by pipeline). */
  embeddingKey?: string;
};

// ─── Object track ─────────────────────────────────────────────────────────────

/**
 * Describes how a specific object moves through the clip.
 * Enables queries like "tank enters frame from left" or "person walks to camera".
 */
export type ObjectTrack = {
  /** Object identifier, e.g. "tank", "Churchill", "Spitfire aircraft". */
  object: string;
  /** Frame position at start: "left" | "center" | "right" | "top" | "bottom" | "offscreen". */
  startPosition: string;
  /** Frame position at end. */
  endPosition: string;
  /** Direction of movement, e.g. "left→right", "towards camera", "away from camera", "stationary". */
  direction: string;
  /** Descriptive movement: "enters frame left", "exits frame right", "crosses frame", "approaches camera". */
  movement: string;
};

// ─── Face track ──────────────────────────────────────────────────────────────

/**
 * Temporal presence of a specific person's face within the clip.
 * Enables precise retrieval of close-ups and dominant-subject shots.
 */
export type FaceTrack = {
  /** Full name if identified, else "unknown person". */
  name: string;
  /** Time (seconds from clip start) when the face first appears. */
  firstAppearsSec: number;
  /** Time (seconds from clip start) when the face last appears. */
  lastAppearsSec: number;
  /** Fraction of total clip duration the face is visible (0–1). */
  dominanceFraction: number;
  /** Duration in seconds where the face is at close-up scale (>50% of frame height). */
  closeUpDurationSec: number;
  /** Whether this person is the primary visual subject of the clip. */
  isPrimarySubject: boolean;
};

// ─── Audio events ─────────────────────────────────────────────────────────────

/**
 * A detected audio event within the clip.
 * Populated by FFmpeg analysis and/or LLM inference.
 */
export type AudioEvent = {
  /**
   * Event type:
   * "applause" | "explosion" | "gunfire" | "speech" | "crowd" | "music"
   * | "silence" | "engines" | "aircraft" | "rain" | "wind" | "gejuich"
   * | "radio" | "march" | string
   */
  type: string;
  /** Approximate start time in seconds (null = throughout). */
  startSec?: number | null;
  /** Approximate duration in seconds. */
  durationSec?: number | null;
  /** Detection confidence 0–1. */
  confidence: number;
};

// ─── Shot importance ──────────────────────────────────────────────────────────

/**
 * Editorial assessment of how important / iconic this clip is.
 * Affects retrieval ranking: iconic clips are surfaced first.
 */
export type ShotImportance = {
  /** Overall importance score 0–100. 100 = Moon landing; 22 = generic skyline. */
  score: number;
  /** Qualitative label: "iconic" (90+), "unique" (70+), "rare" (50+), "generic" (<50). */
  label: "iconic" | "unique" | "rare" | "generic";
  /** One-sentence explanation of this score. */
  reason: string;
};

// ─── Multiple descriptions ────────────────────────────────────────────────────

/**
 * Three description granularities so each consumer uses the right level of detail.
 */
export type ClipDescriptions = {
  /** One sentence. For UI tooltips, search snippets, quick preview. */
  short: string;
  /** One paragraph (3–5 sentences). For standard metadata display. */
  normal: string;
  /** 150–300 words for AI consumers (AssetDirector, Documentary Taste Model). */
  extended: string;
};

// ─── Cinematic tags ──────────────────────────────────────────────────────────

/**
 * Visual and editorial tags for fine-grained retrieval and AssetDirector filtering.
 * These are free-form strings — common values are listed for consistency.
 *
 * Examples: "leading lines", "symmetry", "silhouette", "crowd shot", "aerial view",
 * "skyline", "smoke", "fire", "destruction", "celebration", "interview",
 * "establishing shot", "insert shot", "reaction shot", "cutaway", "b-roll",
 * "portrait", "propaganda", "newsreel", "action", "aftermath", "procession",
 * "ceremony", "ruins", "landscape", "battle", "documentary".
 */
export type CinematicTag = string;

// ─── Visual uniqueness ────────────────────────────────────────────────────────

/**
 * Assessment of how unique/rare this clip is relative to all known footage.
 * Scores 0–100: 100 = Moon landing (one shot ever), 22 = generic city skyline.
 */
export type VisualUniqueness = {
  /** 0–100 uniqueness score. */
  score: number;
  /** One-sentence reasoning. */
  reason: string;
};

// ─── Clip annotation (main type) ─────────────────────────────────────────────

export type ClipAnnotation = {
  /** Annotator version — bump when the prompt changes significantly */
  version: string;

  // ── Personen ──────────────────────────────────────────────────────────────
  persons: {
    /** Known named individuals, e.g. "Churchill", "Hitler", "Kennedy" */
    named: string[];
    /** Generic person categories visible in frame */
    categories: string[];
    // e.g. "soldiers", "civilians", "children", "women", "politicians",
    //      "military officers", "workers", "crowd", "protesters"
  };

  // ── Objecten ─────────────────────────────────────────────────────────────
  objects: string[];
  // e.g. "tank", "aircraft", "ship", "rifle", "flag", "helmet", "church",
  //      "factory", "bridge", "explosion", "fire", "smoke", "ruins"

  // ── Acties ───────────────────────────────────────────────────────────────
  actions: string[];
  // e.g. "marching", "shooting", "running", "speaking", "loading", "flying",
  //      "demonstrating", "cheering", "crying", "waving"

  // ── Omgeving ─────────────────────────────────────────────────────────────
  environment: {
    setting: string;
    // "city" | "village" | "forest" | "desert" | "beach" | "sea" | "sky"
    // | "indoors" | "outdoors" | "office" | "factory" | "battlefield" | "trench"
    isInterior: boolean;
    lighting: string;
    // "daylight" | "night" | "golden hour" | "artificial" | "low key"
  };

  // ── Historische context ───────────────────────────────────────────────────
  historicalContext: {
    /** Best guess at the specific event, e.g. "D-Day landings", "Berlin Wall fall" */
    event: string;
    /** Named historical period, e.g. "World War II", "Cold War", "French Revolution" */
    period: string;
    /** ISO-format if known, else approximate: "1944", "1940s", "20th century" */
    year: string;
    /** Decade, e.g. "1940s" */
    decade: string;
    /** Century, e.g. "20th century" */
    century: string;
  };

  // ── Locatie ───────────────────────────────────────────────────────────────
  location: {
    continent: string;
    country: string;
    region: string;
    city: string;
    /** Confidence: "high" | "medium" | "low" | "unknown" */
    confidence: string;
  };

  // ── Cinematografie ────────────────────────────────────────────────────────
  cinematography: {
    /**
     * "establishing" | "extreme wide" | "wide" | "medium" | "medium close-up"
     * | "close-up" | "extreme close-up"
     */
    shotType: string;
    /**
     * "static" | "handheld" | "pan" | "tilt" | "zoom" | "dolly"
     * | "crane" | "tracking" | "drone" | "orbit"
     */
    cameraMovement: string;
    /**
     * "symmetrical" | "asymmetrical" | "silhouette" | "horizon"
     * | "overhead" | "low angle" | "high angle" | "rule of thirds"
     */
    composition: string;
    /**
     * "archival" | "modern" | "black and white" | "sepia" | "drone"
     * | "illustration" | "map" | "animation" | "newsreel" | "documentary"
     */
    visualStyle: string;
  };

  // ── Emotie & sfeer ────────────────────────────────────────────────────────
  /**
   * Primary emotion conveyed:
   * "tension" | "calm" | "grief" | "triumph" | "defeat" | "fear"
   * | "chaos" | "mystery" | "hope" | "pride" | "awe" | "neutral"
   */
  emotion: string;

  // ── Bewegingsniveau ───────────────────────────────────────────────────────
  /** 0–100: 0 = completely static, 100 = maximum kinetic energy */
  motionLevel: number;

  // ── Visuele kwaliteit ─────────────────────────────────────────────────────
  quality: {
    /** 0–100 overall quality */
    overall: number;
    /** 0–100 sharpness */
    sharpness: number;
    /** 0–100 exposure quality */
    exposure: number;
    /** 0–100 stability (0 = very shaky) */
    stability: number;
    /** 0–100 (100 = pristine, 0 = heavy compression artifacts) */
    compression: number;
  };

  // ── Editorial Score ───────────────────────────────────────────────────────
  editorialScore: {
    /** Overall editorial value 0–100 */
    total: number;
    /** Historical usability: does this clip illustrate a historical moment? */
    historicalUsability: number;
    /** How cinematic/well-composed is the shot? */
    cinematicQuality: number;
    /** Storytelling potential: could this open, develop, or close a scene? */
    storytellingPotential: number;
    /** Emotional value: does it convey a clear, strong emotion? */
    emotionalValue: number;
    /** Movement quality: smooth, purposeful motion scores high */
    movementQuality: number;
    /** Originality: rare/unique content vs. generic stock footage */
    originality: number;
  };

  // ── Hergebruik-hints ─────────────────────────────────────────────────────
  usageHints: {
    /** Best used as: "establishing", "cutaway", "close detail", "transition", "title card" */
    bestUsedAs: string;
    /** Topics this clip pairs well with */
    topicAffinity: string[];
    /** Topics to avoid (e.g. graphic content, wrong era) */
    avoid: string[];
  };

  // ── v2 Archive Intelligence fields (all optional — backward compatible) ──────

  /**
   * 15–25 alternative search phrases that a retrieval system might use to find
   * this clip. Generated by LLM during ingestion.
   * Example: "Churchill speech 1940", "House of Commons wartime address", "British PM WWII"
   */
  searchAliases?: string[];

  /**
   * Flat list of Knowledge Graph entities this clip is connected to.
   * Includes the originating entity + all KG-expanded related terms.
   * Example: ["Churchill", "United Kingdom", "World War II", "1940", "RAF", "Blitz"]
   */
  knowledgeGraphEntities?: string[];

  /**
   * Full editorial description (150–300 words) written for AI consumers.
   * Covers what is visible, who is present, where/when, why it matters,
   * and how it can best be used in a documentary context.
   */
  editorialDescription?: string;

  /**
   * Automatic quality-control flags. Clips with multiple flags receive
   * a lower effective editorial score during retrieval.
   */
  qualityFlags?: ClipQualityFlags;

  /**
   * Confidence scores (0–1) per annotation domain.
   * Used by the Documentary Taste Model to down-weight uncertain annotations.
   */
  confidence?: AnnotationConfidence;

  /**
   * Extended editorial scores (v2). Added alongside the existing editorialScore.
   */
  extendedEditorialScore?: ExtendedEditorialScores;

  /**
   * Keys pointing to per-facet embedding files on disk.
   * Enables targeted semantic retrieval beyond the single full-description embedding.
   */
  facetEmbeddingKeys?: FacetEmbeddingKeys;

  // ── v3 Vision-first fields (all optional — backward compatible) ───────────────

  /**
   * Temporal breakdown of the clip into distinct visual moments.
   * Generated by multi-frame vision analysis. A 10 s clip may have 3–5 segments.
   */
  timeline?: ClipSegment[];

  /**
   * Tracked objects and their movement through the clip.
   * Enables queries like "tank enters frame from left" or "person approaches camera".
   */
  objectTracks?: ObjectTrack[];

  /**
   * Temporal presence of named/unknown faces in the clip.
   * Enables close-up retrieval and dominant-subject filtering.
   */
  faceTracks?: FaceTrack[];

  /**
   * All text strings detected via OCR across multiple frames.
   * Includes: street names, dates, subtitles, posters, newspapers, maps, credits.
   */
  ocrText?: string[];

  /**
   * Audio events detected in the clip (speech, explosions, music, applause, etc.).
   * Populated by FFmpeg analysis and LLM inference.
   */
  audioEvents?: AudioEvent[];

  /**
   * Detailed camera movement description across the clip.
   * More specific than cinematography.cameraMovement — e.g. "slow pan left then zoom in".
   */
  cameraMovementDetail?: string;

  /**
   * Editorial importance assessment: how iconic/rare/unique is this clip?
   * Affects ranking in retrieval — iconic clips are surfaced first.
   */
  shotImportance?: ShotImportance;

  /**
   * Multi-level descriptions for different consumers.
   * Short (1 sentence) → normal (1 paragraph) → extended (150–300 words for AI).
   */
  descriptions?: ClipDescriptions;

  /**
   * Visual and editorial tags for fine-grained retrieval.
   * E.g. ["leading lines", "silhouette", "aerial view", "establishing shot"].
   */
  cinematicTags?: CinematicTag[];

  /**
   * Assessment of how unique this clip is relative to all known footage.
   * 100 = Moon landing; 22 = generic city skyline. Used in ranking.
   */
  visualUniqueness?: VisualUniqueness;
};
