/**
 * RONDE 144 §24 — THE GOLDEN TEST: an edit produces a different MP4.
 *
 * ── Why this test is the whole round ─────────────────────────────────────────────────────────
 *
 * RONDE 139 made the manifest editable and nothing a viewer could see ever changed, because
 * nothing could render from it. The brief's own words: "een prachtige editor die geen nieuwe MP4
 * kan produceren is waardeloos." So the claim this round has to earn is not "the timeline updates"
 * but "the FILE changes, in the way the user asked for".
 *
 * Everything below runs REAL ffmpeg against REAL media and inspects the REAL output with ffprobe.
 * Nothing is mocked. The fixtures are generated by ffmpeg itself (`testsrc`/`smptebars`), so the
 * test needs no network, no API key and no database — which is what makes it runnable in CI and in
 * this environment, where none of the three is configured.
 *
 *     render v1  →  verify
 *     change text          →  render v2  →  verify the frames CHANGED, and only where text is
 *     replace a visual     →  render v3  →  verify the picture changed
 *     re-render v3 as-is   →  verify it is IDENTICAL — §11's determinism
 *
 * ── How "the picture changed" is proved ──────────────────────────────────────────────────────
 *
 * By extracting a PNG frame at a known timestamp from each render and comparing the bytes. That is
 * a real pixel comparison rather than a claim about the command line: an assertion that the ffmpeg
 * arguments differ would pass even if the renderer ignored them.
 */
import { afterAll, beforeAll, describe, expect, it } from "vitest";
import { execFile } from "child_process";
import { promisify } from "util";
import { createHash } from "crypto";
import * as fs from "fs";
import * as os from "os";
import * as path from "path";
import ffmpegStatic from "ffmpeg-static";

import {
  DEFAULT_CAPTION_STYLE,
  DEFAULT_FORMAT,
  DEFAULT_TEXT_STYLE,
  bumpVersion,
  emptyTimeline,
  timelineDigest,
  type ProjectTimeline,
  type TimelineVideoClip,
} from "./projectTimeline";
import {
  checkRenderedFile,
  probeDurationSec,
  renderTimeline,
  TimelineRenderError,
} from "./timelineRenderer";

const execFileAsync = promisify(execFile);
const FFMPEG = (ffmpegStatic as unknown as string) || "ffmpeg";

let ROOT = "";
const media: Record<string, string> = {};

/** A short colour-bars clip, deterministic and generated locally. */
async function makeClip(name: string, pattern: string, seconds: number): Promise<string> {
  const out = path.join(ROOT, `${name}.mp4`);
  await execFileAsync(FFMPEG, [
    "-y", "-hide_banner", "-loglevel", "error",
    "-f", "lavfi", "-i", `${pattern}=size=640x360:rate=25:duration=${seconds}`,
    "-c:v", "libx264", "-preset", "ultrafast", "-pix_fmt", "yuv420p", "-t", String(seconds),
    out,
  ]);
  return out;
}

async function makeTone(name: string, freq: number, seconds: number): Promise<string> {
  const out = path.join(ROOT, `${name}.m4a`);
  await execFileAsync(FFMPEG, [
    "-y", "-hide_banner", "-loglevel", "error",
    "-f", "lavfi", "-i", `sine=frequency=${freq}:duration=${seconds}`,
    "-c:a", "aac", "-b:a", "128k", out,
  ]);
  return out;
}

/** The bytes of one frame, as a hash — the actual picture at that second. */
async function frameHash(video: string, atSec: number): Promise<string> {
  const png = path.join(ROOT, `frame_${createHash("md5").update(video + atSec).digest("hex").slice(0, 8)}.png`);
  await execFileAsync(FFMPEG, [
    "-y", "-hide_banner", "-loglevel", "error",
    "-ss", atSec.toFixed(3), "-i", video, "-frames:v", "1", png,
  ]);
  return createHash("sha256").update(fs.readFileSync(png)).digest("hex");
}

beforeAll(async () => {
  ROOT = fs.mkdtempSync(path.join(os.tmpdir(), "fastvid-golden-"));
  media.shotA = await makeClip("shot_a", "smptebars", 4);
  media.shotB = await makeClip("shot_b", "testsrc", 4);
  media.shotC = await makeClip("shot_c", "testsrc2", 4);
  media.voice = await makeTone("voice", 220, 9);
}, 180_000);

afterAll(() => {
  try {
    fs.rmSync(ROOT, { recursive: true, force: true });
  } catch {
    /* a leftover temp dir is not worth failing a suite over */
  }
});

/** A three-shot timeline with one text overlay and a voice track. */
function buildTimeline(shots: string[]): ProjectTimeline {
  const t = emptyTimeline(4242, { ...DEFAULT_FORMAT, widthPx: 640, heightPx: 360, fps: 25 });
  const clips: TimelineVideoClip[] = shots.map((url, i) => ({
    id: `vc_${i}`,
    kind: "video",
    source: { provider: "test", providerAssetId: `shot${i}`, canonicalUrl: url },
    sourceIn: 0,
    sourceOut: 3,
    timelineStart: i * 3,
    timelineEnd: (i + 1) * 3,
    motion: "none",
    transitionIn: "hard_cut",
    transitionOut: "hard_cut",
    previewSource: "asset",
    sceneIndex: i,
  }));
  t.tracks = [
    { kind: "VIDEO", clips },
    {
      kind: "VOICE",
      clips: [{
        id: "voice_1",
        source: { provider: "elevenlabs", canonicalUrl: media.voice },
        start: 0, end: 9, gain: 1.0,
      }],
    },
    { kind: "MUSIC", clips: [] },
    { kind: "SFX", clips: [] },
    {
      kind: "CAPTIONS",
      captions: [{
        id: "cap_1", text: "the last days of berlin", start: 0.2, end: 2.8,
        style: DEFAULT_CAPTION_STYLE,
      }],
    },
    {
      kind: "TEXT",
      texts: [{
        id: "txt_1", text: "APRIL 1945", start: 3.2, end: 5.8,
        style: { ...DEFAULT_TEXT_STYLE, fontSizePx: 54 }, animation: "fade",
      }],
    },
    { kind: "GRAPHICS", texts: [] },
  ];
  t.durationSec = shots.length * 3;
  return t;
}

const renderTo = async (t: ProjectTimeline, name: string) => {
  const out = path.join(ROOT, `${name}.mp4`);
  const result = await renderTimeline({
    timeline: t,
    workDir: path.join(ROOT, `work_${name}`),
    outputPath: out,
    resolveMedia: async (clip) => clip.source.canonicalUrl ?? null,
    resolveAudio: async (_id, url) => url,
  });
  return { out, result };
};

/* ═══════════════════════ v1 ═══════════════════════ */

describe("GOLDEN §24 — render v1", () => {
  it("produces a real, playable MP4 that matches the timeline", async () => {
    const t = buildTimeline([media.shotA, media.shotB, media.shotC]);
    const { out, result } = await renderTo(t, "v1");

    expect(result.clipsRendered).toBe(3);
    expect(result.textsDrawn).toBe(1);
    expect(result.captionsDrawn).toBe(1);
    expect(result.audioTracks).toBe(1);

    const check = await checkRenderedFile({ filePath: out, timeline: t, expectAudio: true });
    expect(check.problems).toEqual([]);
    expect(check.ok).toBe(true);
    expect(check.hasVideo).toBe(true);
    expect(check.hasAudio).toBe(true);
    expect(check.widthPx).toBe(640);
    expect(check.heightPx).toBe(360);
    expect(check.sizeBytes).toBeGreaterThan(10_000);
    expect(check.durationSec).toBeGreaterThan(8);
  }, 180_000);
});

/* ═══════════════════════ v2 — the text edit ═══════════════════════ */

describe("GOLDEN §24/§16 — change the text, get a different file", () => {
  it("APRIL 1945 → APRIL 1945 — BERLIN changes the PIXELS where the text is", async () => {
    const v1 = buildTimeline([media.shotA, media.shotB, media.shotC]);
    const r1 = await renderTo(v1, "text_v1");

    const v2 = bumpVersion(structuredClone(v1));
    const textTrack = v2.tracks.find((x) => x.kind === "TEXT");
    if (textTrack?.kind === "TEXT") {
      textTrack.texts[0]!.text = "APRIL 1945 — BERLIN";
      textTrack.texts[0]!.editedByUser = true;
    }
    const r2 = await renderTo(v2, "text_v2");

    expect(v2.version).toBe(v1.version + 1);

    // THE ASSERTION: the frame where the overlay sits is a different picture.
    const during1 = await frameHash(r1.out, 4.0);
    const during2 = await frameHash(r2.out, 4.0);
    expect(during2, "the text edit did not reach the pixels").not.toBe(during1);

    // ...and a frame with no text on it is untouched, so the change is the TEXT and not a re-encode
    // that happened to differ everywhere.
    const before1 = await frameHash(r1.out, 1.5);
    const before2 = await frameHash(r2.out, 1.5);
    expect(before2, "a text edit changed a frame that carries no text").toBe(before1);
  }, 240_000);

  it("a caption edit alone does not require the voiceover to be regenerated — §17", async () => {
    /**
     * Asserted as behaviour: the same voice file is handed to both renders, and both come out with
     * an audio stream of the same duration. Nothing in the caption path touches audio.
     */
    const v1 = buildTimeline([media.shotA, media.shotB, media.shotC]);
    const r1 = await renderTo(v1, "cap_v1");
    const v2 = bumpVersion(structuredClone(v1));
    const capTrack = v2.tracks.find((x) => x.kind === "CAPTIONS");
    if (capTrack?.kind === "CAPTIONS") capTrack.captions[0]!.text = "a different caption entirely";
    const r2 = await renderTo(v2, "cap_v2");

    const d1 = await probeDurationSec(r1.out);
    const d2 = await probeDurationSec(r2.out);
    expect(d1).not.toBeNull();
    expect(Math.abs((d2 ?? 0) - (d1 ?? 0))).toBeLessThan(0.4);
    expect(await frameHash(r2.out, 1.5)).not.toBe(await frameHash(r1.out, 1.5));
  }, 240_000);
});

/* ═══════════════════════ v3 — the visual replacement ═══════════════════════ */

describe("GOLDEN §24/§8/§18 — replace a shot, get that shot", () => {
  it("SHOT A → SHOT B changes the picture, and leaves the other shots alone", async () => {
    const v1 = buildTimeline([media.shotA, media.shotB, media.shotC]);
    const r1 = await renderTo(v1, "vis_v1");

    const v3 = bumpVersion(structuredClone(v1));
    const track = v3.tracks.find((x) => x.kind === "VIDEO");
    if (track?.kind === "VIDEO") {
      // §18: the slot keeps its timing; only the source changes.
      track.clips[0]!.source = {
        provider: "archive", archiveAssetId: 99, canonicalUrl: media.shotC,
      };
      track.clips[0]!.editedByUser = true;
    }
    const r3 = await renderTo(v3, "vis_v3");

    // The replaced slot is a different picture...
    expect(await frameHash(r3.out, 1.5)).not.toBe(await frameHash(r1.out, 1.5));
    // ...and the untouched slots are byte-identical.
    expect(await frameHash(r3.out, 7.5)).toBe(await frameHash(r1.out, 7.5));

    // §18: duration is preserved — the replacement was fitted to the slot, not the slot to it.
    const d1 = await probeDurationSec(r1.out);
    const d3 = await probeDurationSec(r3.out);
    expect(Math.abs((d3 ?? 0) - (d1 ?? 0))).toBeLessThan(0.4);
  }, 240_000);

  it("a source SHORTER than its slot is looped to fill it, never left as a gap", async () => {
    // The timeline says how long this shot is. A renderer that produced a shorter clip would be
    // overruling the edit, and every element after it would slip.
    const short = await makeClip("short_one", "smptebars", 1);
    const t = buildTimeline([short, media.shotB]);
    const { out } = await renderTo(t, "loop");
    const d = await probeDurationSec(out);
    expect(d).toBeGreaterThan(5.5);
  }, 240_000);
});

/* ═══════════════════════ §11 — determinism ═══════════════════════ */

describe("GOLDEN §11 — same timeline, same edit", () => {
  it("rendering the same timeline twice produces the same frames", async () => {
    const t = buildTimeline([media.shotA, media.shotB]);
    const a = await renderTo(t, "det_a");
    const b = await renderTo(structuredClone(t), "det_b");
    for (const at of [0.5, 2.0, 4.5]) {
      expect(await frameHash(b.out, at), `frame at ${at}s differed between two runs`).toBe(
        await frameHash(a.out, at)
      );
    }
  }, 240_000);

  it("the digest ignores version and output URL, and follows anything that changes the picture", () => {
    const t = buildTimeline([media.shotA, media.shotB]);
    const same = { ...bumpVersion(structuredClone(t)), renderedVideoUrl: "https://example/x.mp4" };
    expect(timelineDigest(same), "a version bump changed the digest").toBe(timelineDigest(t));

    const edited = structuredClone(t);
    const tt = edited.tracks.find((x) => x.kind === "TEXT");
    if (tt?.kind === "TEXT") tt.texts[0]!.text = "SOMETHING ELSE";
    expect(timelineDigest(edited), "a text edit did not change the digest").not.toBe(
      timelineDigest(t)
    );
  });
});

/* ═══════════════════════ failure is reported, never faked ═══════════════════════ */

describe("GOLDEN — a render that cannot be done says so", () => {
  it("an unrecoverable source is refused rather than silently dropped", async () => {
    const t = buildTimeline([media.shotA]);
    const track = t.tracks.find((x) => x.kind === "VIDEO");
    if (track?.kind === "VIDEO") track.clips[0]!.source = { provider: "pexels" };
    await expect(
      renderTimeline({
        timeline: t,
        workDir: path.join(ROOT, "work_fail"),
        outputPath: path.join(ROOT, "fail.mp4"),
        resolveMedia: async () => null,
      })
    ).rejects.toThrow(TimelineRenderError);
  }, 120_000);

  it("ONE unrecoverable clip out of three is skipped, named, and the rest still render", async () => {
    /**
     * The realistic case for an old manifest: some clips are recoverable and some are not. The
     * render must produce what it can AND say what it could not — a silent hole would leave the
     * user comparing two videos to work out what happened.
     */
    const t = buildTimeline([media.shotA, media.shotB, media.shotC]);
    const track = t.tracks.find((x) => x.kind === "VIDEO");
    if (track?.kind === "VIDEO") track.clips[1]!.source = { provider: "pexels" };
    const out = path.join(ROOT, "partial.mp4");
    const result = await renderTimeline({
      timeline: t,
      workDir: path.join(ROOT, "work_partial"),
      outputPath: out,
      resolveMedia: async (c) => c.source.canonicalUrl ?? null,
      resolveAudio: async (_i, u) => u,
    });
    expect(result.clipsRendered).toBe(2);
    expect(result.skipped.some((s) => s.includes("could not be recovered"))).toBe(true);
    expect(fs.existsSync(out)).toBe(true);
  }, 240_000);

  it("an empty timeline is an error with a name, not an empty file", async () => {
    const t = emptyTimeline(1);
    await expect(
      renderTimeline({
        timeline: t,
        workDir: path.join(ROOT, "work_empty"),
        outputPath: path.join(ROOT, "empty.mp4"),
        resolveMedia: async () => null,
      })
    ).rejects.toMatchObject({ code: "NO_VIDEO_CLIPS" });
  }, 60_000);
});

/* ═══════════════════════ §21 — the gate catches a bad file ═══════════════════════ */

describe("GOLDEN §21 — the post-render gate measures rather than assumes", () => {
  it("a truncated file is caught", async () => {
    const t = buildTimeline([media.shotA, media.shotB]);
    const { out } = await renderTo(t, "gate_ok");
    const broken = path.join(ROOT, "broken.mp4");
    fs.writeFileSync(broken, fs.readFileSync(out).subarray(0, 800));
    const check = await checkRenderedFile({ filePath: broken, timeline: t, expectAudio: true });
    expect(check.ok).toBe(false);
    expect(check.problems.length).toBeGreaterThan(0);
  }, 240_000);

  it("a missing file is caught without throwing", async () => {
    const t = buildTimeline([media.shotA]);
    const check = await checkRenderedFile({
      filePath: path.join(ROOT, "does-not-exist.mp4"), timeline: t, expectAudio: false,
    });
    expect(check.ok).toBe(false);
    expect(check.fileExists).toBe(false);
    expect(check.problems).toContain("output file does not exist");
  });

  it("a timeline with no audio is not reported as missing audio — the gate must not cry wolf", async () => {
    /**
     * RONDE 142 spent a round undoing a check that reported the normal case on every render. A
     * silent timeline is a legitimate thing to render, and `expectAudio` is a parameter for that
     * reason rather than an assumption.
     */
    const t = buildTimeline([media.shotA]);
    t.tracks = t.tracks.map((x) => (x.kind === "VOICE" ? { kind: "VOICE", clips: [] } : x));
    t.durationSec = 3;
    const { out } = await renderTo(t, "silent");
    const check = await checkRenderedFile({ filePath: out, timeline: t, expectAudio: false });
    expect(check.hasAudio).toBe(false);
    expect(check.problems).toEqual([]);
    expect(check.ok).toBe(true);
  }, 180_000);
});
