/**
 * RONDE 144 — THE GOLDEN TEST: TIMELINE → EDIT → RENDER → NEW MP4.
 *
 * ── What this file has to earn ───────────────────────────────────────────────────────────────
 *
 * RONDE 139 made the manifest editable and nothing a viewer could see ever changed, because
 * nothing could render from it. So the claim is not "the timeline updates" but "the FILE changes,
 * in the way the user asked for, and only in that way".
 *
 * Everything below runs REAL ffmpeg against REAL media and inspects the REAL output. Nothing is
 * mocked. Fixtures are generated by ffmpeg itself (`smptebars`/`testsrc`), so this needs no
 * network, no API key and no database — none of which is configured in this environment.
 *
 * ── How the picture is compared, and why not by file size ────────────────────────────────────
 *
 * `regionMaxDiff` decodes ONE FRAME from each of two renders at the same timestamp, crops the same
 * rectangle out of both, and reports the largest luma difference between them on a 0–255 scale
 * (ffmpeg's own `blend=difference` + `signalstats`). That is a statement about what is on the
 * screen at a place and a time. A file size or a whole-file hash cannot distinguish "the text
 * changed" from "the encoder made a different guess", and this can.
 *
 * ── The thresholds are MEASURED, not chosen ──────────────────────────────────────────────────
 *
 * Every number below was read off a real render before it was written into an assertion:
 *
 *     v1 vs v2, at t=4.0s (the overlay is on screen)
 *       TOP band    (no text there)        maxdiff = 0     ← unrelated pixels: untouched
 *       CENTRE band (the changed TEXT)     maxdiff = 255   ← the edit: full contrast
 *       BOTTOM band (the same CAPTION)     maxdiff = 7     ← lossy re-encode bleed only
 *
 *     v1 vs a render with NO text at all, at t=4.0s
 *       CENTRE band                        maxdiff = 226   ← libass really drew characters
 *
 *     v1 vs v2, at t=1.5s (the overlay is NOT yet on screen)
 *       every band                         maxdiff = 0     ← an untouched shot is identical
 *
 * So: CHANGED means ≥ 100, PRESERVED means ≤ 8. Both have a wide margin to the measurement.
 *
 * ── Why libass and not drawtext ──────────────────────────────────────────────────────────────
 *
 * The ffmpeg binary this application ships (`ffmpeg-static` 7.0.2) does NOT have `drawtext` — its
 * build string advertises `--enable-libfreetype` and the filter is absent from `-filters`. The
 * first version of this renderer used drawtext and every text render failed. Nobody had noticed
 * because RONDE 113 switched all ten text engines off. libass is therefore FastVid's text route,
 * and the §LIBASS block below is the proof that it does the job.
 */
import { afterAll, beforeAll, describe, expect, it } from "vitest";
import { execFile } from "child_process";
import { promisify } from "util";
import { createHash } from "crypto";
import * as fs from "fs";
import * as os from "os";
import * as path from "path";
import ffmpegStatic from "ffmpeg-static";

import {
  DEFAULT_CAPTION_STYLE,
  DEFAULT_FORMAT,
  DEFAULT_TEXT_STYLE,
  bumpVersion,
  emptyTimeline,
  timelineDigest,
  type ProjectTimeline,
  type TextStyle,
  type TimelineText,
  type TimelineVideoClip,
} from "./projectTimeline";
import {
  buildAssDocument,
  checkRenderedFile,
  probeDurationSec,
  renderTimeline,
  TimelineRenderError,
} from "./timelineRenderer";

const execFileAsync = promisify(execFile);
const FFMPEG = (ffmpegStatic as unknown as string) || "ffmpeg";

/** A region of the 640×360 frame, as an ffmpeg crop. */
const BAND = {
  /** Nothing is ever drawn here. The control. */
  top: "640:70:0:0",
  /** Where a centred TEXT element lands (ASS alignment 5). */
  centre: "640:110:0:125",
  /** Where a bottom CAPTION lands (ASS alignment 2). */
  bottom: "640:110:0:245",
} as const;

/** Measured on real renders — see the header. */
const CHANGED_AT_LEAST = 100;
const PRESERVED_AT_MOST = 8;

let ROOT = "";
const media: Record<string, string> = {};

async function makeClip(name: string, pattern: string, seconds: number): Promise<string> {
  const out = path.join(ROOT, `${name}.mp4`);
  await execFileAsync(FFMPEG, [
    "-y", "-hide_banner", "-loglevel", "error",
    "-f", "lavfi", "-i", `${pattern}=size=640x360:rate=25:duration=${seconds}`,
    "-c:v", "libx264", "-preset", "ultrafast", "-pix_fmt", "yuv420p", "-t", String(seconds),
    out,
  ]);
  return out;
}

async function makeTone(name: string, freq: number, seconds: number): Promise<string> {
  const out = path.join(ROOT, `${name}.m4a`);
  await execFileAsync(FFMPEG, [
    "-y", "-hide_banner", "-loglevel", "error",
    "-f", "lavfi", "-i", `sine=frequency=${freq}:duration=${seconds}`,
    "-c:a", "aac", "-b:a", "128k", out,
  ]);
  return out;
}

/**
 * The largest luma difference between two renders, in one rectangle, at one instant. 0–255.
 *
 * This is the measurement the whole file rests on. `blend=all_mode=difference` produces the
 * per-pixel absolute difference and `signalstats` reports its maximum, so the answer is about
 * PIXELS rather than about bytes, headers or encoder settings.
 */
async function regionMaxDiff(a: string, b: string, atSec: number, crop: string): Promise<number> {
  const { stderr } = await execFileAsync(
    FFMPEG,
    [
      "-hide_banner", "-loglevel", "info",
      "-ss", atSec.toFixed(3), "-i", a,
      "-ss", atSec.toFixed(3), "-i", b,
      "-filter_complex",
      `[0:v]crop=${crop},format=gray[x];[1:v]crop=${crop},format=gray[y];` +
        `[x][y]blend=all_mode=difference,signalstats,metadata=print:key=lavfi.signalstats.YMAX`,
      "-frames:v", "1", "-f", "null", "-",
    ],
    { maxBuffer: 1024 * 1024 * 32 }
  );
  const m = /YMAX=(\d+)/.exec(stderr);
  if (!m) throw new Error(`could not measure region ${crop} at ${atSec}s`);
  return Number(m[1]);
}

/** The whole file, byte for byte. */
function fileSha(p: string): string {
  return createHash("sha256").update(fs.readFileSync(p)).digest("hex");
}

beforeAll(async () => {
  ROOT = fs.mkdtempSync(path.join(os.tmpdir(), "fastvid-golden-"));
  media.shotA = await makeClip("shot_a", "smptebars", 4);
  media.shotB = await makeClip("shot_b", "testsrc", 4);
  media.shotC = await makeClip("shot_c", "testsrc2", 4);
  media.voice = await makeTone("voice", 220, 9);
}, 300_000);

afterAll(() => {
  try {
    fs.rmSync(ROOT, { recursive: true, force: true });
  } catch {
    /* a leftover temp dir is not worth failing a suite over */
  }
});

/**
 * A three-shot timeline: one centred TEXT element (3.2–5.8s), one bottom CAPTION (0.2–2.8s),
 * and a voice track. `text: null` builds the same thing with no TEXT element at all — the control
 * that proves the characters are really being drawn.
 */
function buildTimeline(shots: string[], text: string | null = "APRIL 1945"): ProjectTimeline {
  const t = emptyTimeline(4242, { ...DEFAULT_FORMAT, widthPx: 640, heightPx: 360, fps: 25 });
  const clips: TimelineVideoClip[] = shots.map((url, i) => ({
    id: `vc_${i}`,
    kind: "video",
    source: { provider: "test", providerAssetId: `shot${i}`, canonicalUrl: url },
    sourceIn: 0,
    sourceOut: 3,
    timelineStart: i * 3,
    timelineEnd: (i + 1) * 3,
    motion: "none",
    transitionIn: "hard_cut",
    transitionOut: "hard_cut",
    previewSource: "asset",
    sceneIndex: i,
  }));
  t.tracks = [
    { kind: "VIDEO", clips },
    {
      kind: "VOICE",
      clips: [{
        id: "voice_1",
        source: { provider: "elevenlabs", canonicalUrl: media.voice },
        start: 0, end: 9, gain: 1.0,
      }],
    },
    { kind: "MUSIC", clips: [] },
    { kind: "SFX", clips: [] },
    {
      kind: "CAPTIONS",
      captions: [{
        id: "cap_1", text: "the last days of berlin", start: 0.2, end: 2.8,
        style: DEFAULT_CAPTION_STYLE,
      }],
    },
    {
      kind: "TEXT",
      texts: text
        ? [{
            id: "txt_1", text, start: 3.2, end: 5.8,
            style: { ...DEFAULT_TEXT_STYLE, fontSizePx: 54 }, animation: "fade",
          }]
        : [],
    },
    { kind: "GRAPHICS", texts: [] },
  ];
  t.durationSec = shots.length * 3;
  return t;
}

async function renderTo(t: ProjectTimeline, name: string) {
  const out = path.join(ROOT, `${name}.mp4`);
  const workDir = path.join(ROOT, `work_${name}`);
  const result = await renderTimeline({
    timeline: t,
    workDir,
    outputPath: out,
    resolveMedia: async (clip) => clip.source.canonicalUrl ?? null,
    resolveAudio: async (_id, url) => url,
  });
  return { out, workDir, result };
}

/* ═════════════════════════════ TEST 1 — the original render ═════════════════════════════ */

describe("TEST 1 — timeline v1 → render → a valid MP4", () => {
  it("produces a real, playable MP4 whose properties match the timeline", async () => {
    const t = buildTimeline([media.shotA, media.shotB, media.shotC]);
    const { out, result } = await renderTo(t, "t1_v1");

    expect(result.clipsRendered).toBe(3);
    expect(result.textsDrawn).toBe(1);
    expect(result.captionsDrawn).toBe(1);
    expect(result.audioTracks).toBe(1);
    expect(result.skipped).toEqual([]);

    const check = await checkRenderedFile({ filePath: out, timeline: t, expectAudio: true });
    expect(check.problems).toEqual([]);
    expect(check.ok).toBe(true);
    expect(check.hasVideo).toBe(true);
    expect(check.hasAudio).toBe(true);
    expect(check.widthPx).toBe(640);
    expect(check.heightPx).toBe(360);
    expect(check.fps).toBeCloseTo(25, 0);
    expect(check.sizeBytes).toBeGreaterThan(10_000);
    expect(check.durationSec).toBeGreaterThan(8.5);
  }, 300_000);
});

/* ═════════════════════════════ TEST 2 — the text edit ═════════════════════════════ */

describe("TEST 2 — change one text element → v2 → the PIXELS change, and only there", () => {
  it("the text is actually VISIBLE: the centre band differs from a render with no text", async () => {
    /**
     * Asked first, because every other assertion in this block would also pass if libass drew
     * nothing and the two renders merely differed. This compares against a control that has no
     * TEXT element at all, so the difference IS the characters.
     */
    const withText = await renderTo(buildTimeline([media.shotA, media.shotB], "APRIL 1945"), "t2_with");
    const noText = await renderTo(buildTimeline([media.shotA, media.shotB], null), "t2_without");

    const drawn = await regionMaxDiff(withText.out, noText.out, 4.0, BAND.centre);
    expect(drawn, "libass drew nothing where the text should be").toBeGreaterThanOrEqual(
      CHANGED_AT_LEAST
    );
    // ...and it drew it where it was asked to, not somewhere else.
    const elsewhere = await regionMaxDiff(withText.out, noText.out, 4.0, BAND.top);
    expect(elsewhere, "text appeared outside its own region").toBeLessThanOrEqual(PRESERVED_AT_MOST);
  }, 300_000);

  it("APRIL 1945 → APRIL 1945 — BERLIN: the text region changes", async () => {
    const v1 = buildTimeline([media.shotA, media.shotB], "APRIL 1945");
    const r1 = await renderTo(v1, "t2_v1");

    const v2 = bumpVersion(structuredClone(v1));
    const textTrack = v2.tracks.find((x) => x.kind === "TEXT");
    if (textTrack?.kind === "TEXT") {
      textTrack.texts[0]!.text = "APRIL 1945 — BERLIN";
      textTrack.texts[0]!.editedByUser = true;
    }
    const r2 = await renderTo(v2, "t2_v2");
    expect(v2.version).toBe(v1.version + 1);

    const changed = await regionMaxDiff(r1.out, r2.out, 4.0, BAND.centre);
    expect(changed, "the text edit never reached the pixels").toBeGreaterThanOrEqual(
      CHANGED_AT_LEAST
    );
  }, 300_000);

  it("pixels OUTSIDE the text region do not change", async () => {
    /**
     * The half that makes the previous assertion mean something. A renderer that re-encoded the
     * whole video differently would also "change the pixels where the text is" — and would change
     * everything else too. Two bands are checked: one in the same frame (spatial isolation) and
     * one at a timestamp before the element exists (temporal isolation).
     */
    const v1 = buildTimeline([media.shotA, media.shotB], "APRIL 1945");
    const r1 = await renderTo(v1, "t2b_v1");
    const v2 = bumpVersion(structuredClone(v1));
    const tt = v2.tracks.find((x) => x.kind === "TEXT");
    if (tt?.kind === "TEXT") tt.texts[0]!.text = "APRIL 1945 — BERLIN";
    const r2 = await renderTo(v2, "t2b_v2");

    const sameFrameElsewhere = await regionMaxDiff(r1.out, r2.out, 4.0, BAND.top);
    expect(sameFrameElsewhere, "a text edit disturbed the rest of the frame").toBeLessThanOrEqual(
      PRESERVED_AT_MOST
    );

    for (const band of Object.values(BAND)) {
      const beforeTheElement = await regionMaxDiff(r1.out, r2.out, 1.5, band);
      expect(
        beforeTheElement,
        `a text edit changed a frame at 1.5s, before the element exists (band ${band})`
      ).toBeLessThanOrEqual(PRESERVED_AT_MOST);
    }
  }, 300_000);

  it("editing a CAPTION does not require the voiceover to be regenerated", async () => {
    // §17. The same voice file is handed to both renders and the durations match; nothing in the
    // caption path touches audio.
    const v1 = buildTimeline([media.shotA, media.shotB]);
    const r1 = await renderTo(v1, "t2c_v1");
    const v2 = bumpVersion(structuredClone(v1));
    const cap = v2.tracks.find((x) => x.kind === "CAPTIONS");
    if (cap?.kind === "CAPTIONS") cap.captions[0]!.text = "a completely different caption";
    const r2 = await renderTo(v2, "t2c_v2");

    const d1 = await probeDurationSec(r1.out);
    const d2 = await probeDurationSec(r2.out);
    expect(Math.abs((d2 ?? 0) - (d1 ?? 0))).toBeLessThan(0.4);
    // The caption band changed; the band above it did not.
    expect(await regionMaxDiff(r1.out, r2.out, 1.5, BAND.bottom)).toBeGreaterThanOrEqual(
      CHANGED_AT_LEAST
    );
    expect(await regionMaxDiff(r1.out, r2.out, 1.5, BAND.top)).toBeLessThanOrEqual(
      PRESERVED_AT_MOST
    );
  }, 300_000);
});

/* ═════════════════════════════ TEST 3 — the shot replacement ═════════════════════════════ */

describe("TEST 3 — replace one video asset → v3 → that shot changes and no other", () => {
  it("the replaced shot is a different picture; the untouched shots are identical", async () => {
    const v2 = buildTimeline([media.shotA, media.shotB, media.shotC]);
    const r2 = await renderTo(v2, "t3_v2");

    const v3 = bumpVersion(structuredClone(v2));
    const track = v3.tracks.find((x) => x.kind === "VIDEO");
    if (track?.kind === "VIDEO") {
      // §18: the slot keeps its timing, its motion and its transitions. Only the source moves.
      track.clips[0]!.source = { provider: "archive", archiveAssetId: 99, canonicalUrl: media.shotC };
      track.clips[0]!.editedByUser = true;
    }
    const r3 = await renderTo(v3, "t3_v3");

    // Shot 0 (0–3s) was replaced: the whole frame is a different picture.
    const replaced = await regionMaxDiff(r2.out, r3.out, 1.5, BAND.top);
    expect(replaced, "the replacement never reached the pixels").toBeGreaterThanOrEqual(
      CHANGED_AT_LEAST
    );

    // Shots 1 and 2 (3–6s, 6–9s) were not touched: identical, in every band.
    for (const at of [4.5, 7.5]) {
      for (const band of Object.values(BAND)) {
        const diff = await regionMaxDiff(r2.out, r3.out, at, band);
        expect(diff, `an untouched shot changed at ${at}s (band ${band})`).toBeLessThanOrEqual(
          PRESERVED_AT_MOST
        );
      }
    }
  }, 420_000);

  it("timing does not change: the slot was fitted to the clip, not the clip to the slot", async () => {
    const v2 = buildTimeline([media.shotA, media.shotB, media.shotC]);
    const r2 = await renderTo(v2, "t3b_v2");
    const v3 = bumpVersion(structuredClone(v2));
    const track = v3.tracks.find((x) => x.kind === "VIDEO");
    // A source of a DIFFERENT length from the one it replaces — the case where a renderer that
    // took the source's duration instead of the slot's would shift everything after it.
    const shortSource = await makeClip("t3_short", "smptebars", 1);
    if (track?.kind === "VIDEO") track.clips[0]!.source = { provider: "x", canonicalUrl: shortSource };
    const r3 = await renderTo(v3, "t3b_v3");

    const d2 = await probeDurationSec(r2.out);
    const d3 = await probeDurationSec(r3.out);
    expect(Math.abs((d3 ?? 0) - (d2 ?? 0))).toBeLessThan(0.4);

    // And the shots AFTER the replacement are still at the same timestamps.
    expect(await regionMaxDiff(r2.out, r3.out, 7.5, BAND.top)).toBeLessThanOrEqual(
      PRESERVED_AT_MOST
    );
  }, 420_000);
});

/* ═════════════════════════════ TEST 4 — determinism ═════════════════════════════ */

describe("TEST 4 — same timeline + same assets + same settings = same output", () => {
  it("BIT FOR BIT: two renders of the same timeline produce byte-identical files", async () => {
    /**
     * The strongest available form, and it holds — no `-bitexact` flag needed. Attempted first
     * exactly as the brief asks; the weaker frame-level comparison below is kept as well, so a
     * future ffmpeg that stamps something into the container degrades this suite to "the picture
     * is identical" rather than breaking it.
     *
     * Note the two renders use DIFFERENT work directories, so the ASS file lives at a different
     * path in each — proving the overlay path does not leak into the output.
     */
    const t = buildTimeline([media.shotA, media.shotB]);
    const a = await renderTo(t, "t4_a");
    const b = await renderTo(structuredClone(t), "t4_b");
    expect(a.workDir).not.toBe(b.workDir);
    expect(fileSha(b.out), "two renders of one timeline differed byte for byte").toBe(
      fileSha(a.out)
    );
  }, 300_000);

  it("...and the frames are identical too, measured rather than inferred", async () => {
    const t = buildTimeline([media.shotA, media.shotB]);
    const a = await renderTo(t, "t4c_a");
    const b = await renderTo(structuredClone(t), "t4c_b");
    for (const at of [0.5, 1.5, 4.0, 5.5]) {
      for (const band of Object.values(BAND)) {
        expect(
          await regionMaxDiff(a.out, b.out, at, band),
          `two runs differed at ${at}s in band ${band}`
        ).toBe(0);
      }
    }
  }, 300_000);

  it("the digest tracks what changes the picture and ignores what does not", () => {
    const t = buildTimeline([media.shotA, media.shotB]);
    const same = { ...bumpVersion(structuredClone(t)), renderedVideoUrl: "https://example/x.mp4" };
    expect(timelineDigest(same), "a version bump changed the digest").toBe(timelineDigest(t));

    const edited = structuredClone(t);
    const tt = edited.tracks.find((x) => x.kind === "TEXT");
    if (tt?.kind === "TEXT") tt.texts[0]!.text = "SOMETHING ELSE";
    expect(timelineDigest(edited), "a text edit did not change the digest").not.toBe(
      timelineDigest(t)
    );
  });
});

/* ═════════════════════════════ LIBASS ═════════════════════════════ */

describe("LIBASS — the text route this build actually has", () => {
  const styleAt = (position: TextStyle["position"], size = 46): TextStyle => ({
    ...DEFAULT_TEXT_STYLE,
    fontSizePx: size,
    position,
    maxCharsPerLine: 30,
  });

  /**
   * MEASURED band geometry, not arithmetic.
   *
   * A row-by-row scan of real renders at fontSize 46 found the ink here:
   *
   *     position "top"      rows  40– 79
   *     position "center"   rows 160–199
   *     position "bottom"   rows 260–319
   *     a wrapped block     rows  80–279
   *
   * The bands below are cut to those measurements. My first attempt derived them from font size
   * and margin and put the "top" band at rows 0–69, which overlapped the top text by half — the
   * kind of error that makes a position test pass for the wrong reason.
   */
  const INK = {
    /** No element of any position ever reaches here. The control. */
    control: "640:25:0:0",
    top: "640:60:0:30",
    centre: "640:60:0:150",
    bottom: "640:80:0:250",
    /** Only a WRAPPED block reaches this high; a single centred line does not. */
    aboveCentre: "640:50:0:90",
  } as const;

  /**
   * A text element parked far outside the video's own duration.
   *
   * ── The confound this removes, measured ─────────────────────────────────────────────────────
   *
   * The renderer SKIPS the libass pass when a timeline has no text at all — the concat output is
   * stream-copied straight through. So a naive "no text" control is encoded ONCE while the render
   * being tested is encoded TWICE, and on an animated source that generation difference alone
   * measures up to 14 in regions where nothing was drawn. Three assertions in this block failed at
   * 13, 19 and 32 for exactly that reason, and every one of them was the TEST being wrong rather
   * than the renderer.
   *
   * Measured, on an animated source, in a band with no text in it:
   *
   *     one pass  vs two passes   YMAX = 14      ← the confound
   *     two passes vs two passes  YMAX =  0      ← removed
   *
   * This element makes the control take the identical path while drawing nothing: libass runs, the
   * frame is re-encoded, and the event's window (99s) never arrives in a nine-second video.
   *
   * Raising the threshold instead would have been the wrong repair — it would have hidden a real
   * 14-unit difference behind a bigger number rather than explaining it.
   */
  const OFFSCREEN: TimelineText = {
    id: "offscreen_control",
    text: "never visible",
    start: 99,
    end: 99.5,
    style: DEFAULT_TEXT_STYLE,
    animation: "none",
  };

  /**
   * A STATIC background, deliberately.
   *
   * ── The second confound, also measured ──────────────────────────────────────────────────────
   *
   * x264's rate control is frame-global: change anything in a frame and the encoder re-spends its
   * bits across the WHOLE frame. On a moving source that shows up in regions where nothing was
   * drawn. Measured, comparing two renders that differ only in a text element at the TOP, in bands
   * far away from it:
   *
   *     smptebars (static)   clean bands = 0, 0
   *     testsrc   (animated) clean bands = 0, 10
   *
   * That is the real reason the position, wrapping and multi-element assertions kept landing at
   * 18-29 rather than under 8 — not the encode-pass count, which was my first guess and which
   * measured only 1-2 on its own.
   *
   * This block is about WHERE libass puts ink and WHEN. The background's motion contributes
   * nothing to that claim and only adds noise, so these fixtures use the static pattern for both
   * shots. TEST 1-4 keep the mixed sources, because there the comparisons are either on the static
   * shot or expect a large change.
   */
  const withTexts = (texts: TimelineText[]): ProjectTimeline => {
    const t = buildTimeline([media.shotA, media.shotA], null);
    const tt = t.tracks.find((x) => x.kind === "TEXT");
    // The control gets OFFSCREEN so that every render in this block takes the same encode path.
    if (tt?.kind === "TEXT") tt.texts = texts.length > 0 ? texts : [OFFSCREEN];
    const cap = t.tracks.find((x) => x.kind === "CAPTIONS");
    if (cap?.kind === "CAPTIONS") cap.captions = [];
    return t;
  };

  it("drawtext is genuinely absent from the shipped binary — the reason this route exists", async () => {
    /**
     * Asserted rather than remembered. If a future ffmpeg-static gains drawtext this test turns
     * red and someone gets to make a deliberate choice, instead of the comment slowly becoming
     * false while nobody notices.
     */
    const { stdout } = await execFileAsync(FFMPEG, ["-hide_banner", "-filters"], {
      maxBuffer: 1024 * 1024 * 8,
    });
    expect(/\bsubtitles\b/.test(stdout), "libass is missing — text cannot be rendered at all").toBe(
      true
    );
    expect(
      /\bdrawtext\b/.test(stdout),
      "drawtext is available again — reconsider the text route deliberately"
    ).toBe(false);
  }, 60_000);

  it("plain text renders", async () => {
    const t = withTexts([
      { id: "a", text: "BERLIN", start: 1.0, end: 5.0, style: styleAt("center"), animation: "none" },
    ]);
    const withT = await renderTo(t, "la_plain");
    const without = await renderTo(withTexts([]), "la_none");
    expect(await regionMaxDiff(withT.out, without.out, 3.0, INK.centre)).toBeGreaterThanOrEqual(
      CHANGED_AT_LEAST
    );
    expect(await regionMaxDiff(withT.out, without.out, 3.0, INK.control)).toBeLessThanOrEqual(
      PRESERVED_AT_MOST
    );
  }, 300_000);

  it("a long sentence wraps onto MULTIPLE LINES instead of running off the frame", async () => {
    /**
     * Proved by geometry rather than by trusting the wrapper: a single line at this size occupies
     * one band, and a wrapped one must also mark the band above it. If the text ran off the sides
     * instead of wrapping, the upper band would be untouched.
     */
    const long =
      "in april 1945 soviet forces closed in on the capital from three directions at once";
    const one = await renderTo(
      withTexts([{ id: "s", text: "BERLIN", start: 1, end: 5, style: styleAt("center"), animation: "none" }]),
      "la_one"
    );
    const many = await renderTo(
      withTexts([{ id: "l", text: long, start: 1, end: 5, style: styleAt("center"), animation: "none" }]),
      "la_many"
    );
    // Geometry, measured: a single centred line occupies rows 160-199 and a wrapped block reaches
    // up to row 80. So the band at rows 90-139 separates them.
    const noText = await renderTo(withTexts([]), "la_none2");
    expect(
      await regionMaxDiff(many.out, noText.out, 3.0, INK.aboveCentre),
      "a long sentence did not wrap onto more lines"
    ).toBeGreaterThanOrEqual(CHANGED_AT_LEAST);
    expect(
      await regionMaxDiff(one.out, noText.out, 3.0, INK.aboveCentre),
      "the single-line control unexpectedly filled the band above the centre"
    ).toBeLessThanOrEqual(PRESERVED_AT_MOST);
  }, 420_000);

  it("POSITION is honoured: top, centre and bottom land in different places", async () => {
    const noText = await renderTo(withTexts([]), "la_none3");
    const at = async (position: TextStyle["position"], tag: string) =>
      renderTo(
        withTexts([
          { id: "p", text: "EASTERN FRONT", start: 1, end: 5, style: styleAt(position), animation: "none" },
        ]),
        `la_pos_${tag}`
      );

    const top = await at("top", "top");
    expect(await regionMaxDiff(top.out, noText.out, 3.0, INK.top)).toBeGreaterThanOrEqual(
      CHANGED_AT_LEAST
    );
    expect(await regionMaxDiff(top.out, noText.out, 3.0, INK.centre)).toBeLessThanOrEqual(
      PRESERVED_AT_MOST
    );
    expect(await regionMaxDiff(top.out, noText.out, 3.0, INK.bottom)).toBeLessThanOrEqual(
      PRESERVED_AT_MOST
    );

    const centre = await at("center", "ctr");
    expect(await regionMaxDiff(centre.out, noText.out, 3.0, INK.centre)).toBeGreaterThanOrEqual(
      CHANGED_AT_LEAST
    );
    expect(await regionMaxDiff(centre.out, noText.out, 3.0, INK.top)).toBeLessThanOrEqual(
      PRESERVED_AT_MOST
    );

    const bottom = await at("bottom", "bot");
    expect(await regionMaxDiff(bottom.out, noText.out, 3.0, INK.bottom)).toBeGreaterThanOrEqual(
      CHANGED_AT_LEAST
    );
    expect(await regionMaxDiff(bottom.out, noText.out, 3.0, INK.top)).toBeLessThanOrEqual(
      PRESERVED_AT_MOST
    );
  }, 420_000);

  it("FADE is applied: the first frame of an element is not the same as its middle", async () => {
    /**
     * A 220ms fade means the element is partly transparent when it appears. Comparing a frame just
     * after the start against one in the middle of the SAME render isolates the animation: the
     * underlying picture is a static shot, so anything that differs is the fade.
     */
    const t = withTexts([
      { id: "f", text: "THE FINAL DAYS", start: 1.0, end: 5.0, style: styleAt("center"), animation: "fade" },
    ]);
    const r = await renderTo(t, "la_fade");
    // shot A is smptebars — static — so the same band at two times is identical unless something
    // was drawn differently.
    const early = await regionMaxDiff(r.out, r.out, 1.04, INK.centre); // sanity: same frame = 0
    expect(early).toBe(0);
    const diff = await execFileAsync(
      FFMPEG,
      [
        "-hide_banner", "-loglevel", "info",
        "-ss", "1.04", "-i", r.out, "-ss", "3.00", "-i", r.out,
        "-filter_complex",
        `[0:v]crop=${INK.centre},format=gray[x];[1:v]crop=${INK.centre},format=gray[y];` +
          `[x][y]blend=all_mode=difference,signalstats,metadata=print:key=lavfi.signalstats.YMAX`,
        "-frames:v", "1", "-f", "null", "-",
      ],
      { maxBuffer: 1024 * 1024 * 32 }
    );
    const m = /YMAX=(\d+)/.exec(diff.stderr);
    expect(Number(m?.[1] ?? 0), "the fade produced no visible ramp").toBeGreaterThan(20);
  }, 300_000);

  it("SEVERAL text elements in ONE render each appear in their own window", async () => {
    const t = withTexts([
      { id: "1", text: "APRIL 1945", start: 0.5, end: 2.0, style: styleAt("center"), animation: "none" },
      { id: "2", text: "BERLIN", start: 2.5, end: 4.0, style: styleAt("top"), animation: "none" },
      { id: "3", text: "2.5 MILLION", start: 4.5, end: 5.8, style: styleAt("bottom"), animation: "none" },
    ]);
    const r = await renderTo(t, "la_multi");
    const noText = await renderTo(withTexts([]), "la_none4");

    expect(await regionMaxDiff(r.out, noText.out, 1.2, INK.centre)).toBeGreaterThanOrEqual(CHANGED_AT_LEAST);
    expect(await regionMaxDiff(r.out, noText.out, 3.2, INK.top)).toBeGreaterThanOrEqual(CHANGED_AT_LEAST);
    expect(await regionMaxDiff(r.out, noText.out, 5.2, INK.bottom)).toBeGreaterThanOrEqual(CHANGED_AT_LEAST);
    // ...and each is GONE outside its own window.
    expect(await regionMaxDiff(r.out, noText.out, 2.2, INK.centre)).toBeLessThanOrEqual(PRESERVED_AT_MOST);
    expect(await regionMaxDiff(r.out, noText.out, 5.2, INK.top)).toBeLessThanOrEqual(PRESERVED_AT_MOST);
    expect(await regionMaxDiff(r.out, noText.out, 1.2, INK.bottom)).toBeLessThanOrEqual(PRESERVED_AT_MOST);
  }, 420_000);

  it("ONE ASS file carries the whole render, and it is well-formed", async () => {
    const t = withTexts([
      { id: "1", text: "APRIL 1945", start: 0.5, end: 2.0, style: styleAt("center"), animation: "fade" },
      { id: "2", text: "BERLIN", start: 2.5, end: 4.0, style: styleAt("top"), animation: "none" },
      { id: "3", text: "SAME LOOK", start: 4.5, end: 5.5, style: styleAt("top"), animation: "none" },
    ]);
    const r = await renderTo(t, "la_onefile");
    const assFiles = fs.readdirSync(r.workDir).filter((f) => f.endsWith(".ass"));
    expect(assFiles, "expected exactly one subtitle document per render").toHaveLength(1);

    const doc = fs.readFileSync(path.join(r.workDir, assFiles[0]!), "utf8");
    expect(doc).toContain("[Script Info]");
    expect(doc).toContain("PlayResX: 640");
    expect(doc).toContain("PlayResY: 360");
    expect((doc.match(/^Dialogue:/gm) ?? [])).toHaveLength(3);
    // Two of the three share a style, so there must be FEWER style lines than events.
    const styles = doc.match(/^Style:/gm) ?? [];
    expect(styles.length).toBe(2);
  }, 300_000);

  it("the document generator handles the characters that would break it", () => {
    /**
     * Pure, so the awkward cases can be checked exhaustively without an encode. Braces are ASS's
     * override syntax and have no escape, so they are replaced; a caption that silently vanished
     * would be far worse than one with round brackets.
     */
    const doc = buildAssDocument({
      elements: [
        {
          text: "it's 50% — {\\pos(0,0)} \"done\": now\nand a second line",
          start: 0, end: 2, style: DEFAULT_CAPTION_STYLE,
        },
      ],
      widthPx: 640, heightPx: 360,
    });
    const dialogue = (doc.match(/^Dialogue:.*$/m) ?? [""])[0];
    expect(dialogue).toContain("it's 50%");
    expect(dialogue, "an override block survived into the text").not.toContain("{\\pos");
    expect(dialogue).toContain("(");
    expect(dialogue, "a newline broke the Dialogue line in two").not.toContain("\n");
    expect(doc.match(/^Dialogue:/gm)).toHaveLength(1);
  });

  it("an empty or whitespace-only element is dropped rather than drawn", () => {
    const doc = buildAssDocument({
      elements: [
        { text: "   ", start: 0, end: 2, style: DEFAULT_CAPTION_STYLE },
        { text: "real", start: 3, end: 1, style: DEFAULT_CAPTION_STYLE }, // end before start
        { text: "kept", start: 0, end: 2, style: DEFAULT_CAPTION_STYLE },
      ],
      widthPx: 640, heightPx: 360,
    });
    expect(doc.match(/^Dialogue:/gm)).toHaveLength(1);
    expect(doc).toContain("kept");
  });
});

/* ═════════════════════════════ failure is reported, never faked ═════════════════════════════ */

describe("GOLDEN — a render that cannot be done says so", () => {
  it("an unrecoverable source is refused rather than silently dropped", async () => {
    const t = buildTimeline([media.shotA]);
    const track = t.tracks.find((x) => x.kind === "VIDEO");
    if (track?.kind === "VIDEO") track.clips[0]!.source = { provider: "pexels" };
    await expect(
      renderTimeline({
        timeline: t,
        workDir: path.join(ROOT, "work_fail"),
        outputPath: path.join(ROOT, "fail.mp4"),
        resolveMedia: async () => null,
      })
    ).rejects.toThrow(TimelineRenderError);
  }, 120_000);

  it("ONE unrecoverable clip out of three is skipped, NAMED, and the rest still render", async () => {
    const t = buildTimeline([media.shotA, media.shotB, media.shotC]);
    const track = t.tracks.find((x) => x.kind === "VIDEO");
    if (track?.kind === "VIDEO") track.clips[1]!.source = { provider: "pexels" };
    const out = path.join(ROOT, "partial.mp4");
    const result = await renderTimeline({
      timeline: t,
      workDir: path.join(ROOT, "work_partial"),
      outputPath: out,
      resolveMedia: async (c) => c.source.canonicalUrl ?? null,
      resolveAudio: async (_i, u) => u,
    });
    expect(result.clipsRendered).toBe(2);
    expect(result.skipped.some((s) => s.includes("could not be recovered"))).toBe(true);
    expect(fs.existsSync(out)).toBe(true);
  }, 300_000);

  it("an empty timeline is an error with a name, not an empty file", async () => {
    await expect(
      renderTimeline({
        timeline: emptyTimeline(1),
        workDir: path.join(ROOT, "work_empty"),
        outputPath: path.join(ROOT, "empty.mp4"),
        resolveMedia: async () => null,
      })
    ).rejects.toMatchObject({ code: "NO_VIDEO_CLIPS" });
  }, 60_000);
});

/* ═════════════════════════════ the post-render gate ═════════════════════════════ */

describe("GOLDEN — the post-render gate measures rather than assumes", () => {
  it("a truncated file is caught", async () => {
    const t = buildTimeline([media.shotA, media.shotB]);
    const { out } = await renderTo(t, "gate_ok");
    const broken = path.join(ROOT, "broken.mp4");
    fs.writeFileSync(broken, fs.readFileSync(out).subarray(0, 800));
    const check = await checkRenderedFile({ filePath: broken, timeline: t, expectAudio: true });
    expect(check.ok).toBe(false);
    expect(check.problems.length).toBeGreaterThan(0);
  }, 300_000);

  it("a missing file is caught without throwing", async () => {
    const check = await checkRenderedFile({
      filePath: path.join(ROOT, "does-not-exist.mp4"),
      timeline: buildTimeline([media.shotA]),
      expectAudio: false,
    });
    expect(check.ok).toBe(false);
    expect(check.fileExists).toBe(false);
    expect(check.problems).toContain("output file does not exist");
  });

  it("a timeline with no audio is not reported as missing audio — the gate must not cry wolf", async () => {
    const t = buildTimeline([media.shotA]);
    t.tracks = t.tracks.map((x) => (x.kind === "VOICE" ? { kind: "VOICE", clips: [] } : x));
    t.durationSec = 3;
    const { out } = await renderTo(t, "silent");
    const check = await checkRenderedFile({ filePath: out, timeline: t, expectAudio: false });
    expect(check.hasAudio).toBe(false);
    expect(check.problems).toEqual([]);
    expect(check.ok).toBe(true);
  }, 300_000);
});
