/**
 * RONDE 182 — the showcase: one video, planned by the real route and rendered to real pixels.
 *
 * ── What this is for ─────────────────────────────────────────────────────────────────────────
 *
 * Every other test in this series proves one link. R160 rendered graphics, R160 §8 rendered editing
 * operations, R178 proved the plan reaches the timeline. None of them answers the question the
 * quality gate actually asks: does a video go all the way from a script's beats to a finished file,
 * through the code production runs, with the cinematic decisions visible in the output.
 *
 * So this builds ONE video the whole way:
 *
 *     beat text + adopted clips
 *       → buildCinematicSceneInputs   with the production extractors
 *       → runCinematicPipeline        Director, EDL, planners, translation
 *       → ProjectTimeline             the single source of truth
 *       → renderTimeline              real ffmpeg, real Remotion overlay when available
 *       → an mp4, measured
 *
 * ── What is synthetic, and what is not ───────────────────────────────────────────────────────
 *
 * The MEDIA is synthetic: flat-coloured clips generated by ffmpeg, because this environment has no
 * provider keys and because a flat colour answers "is this frame the second clip" with certainty
 * where documentary footage answers it with a judgement call.
 *
 * Nothing else is stubbed. The planners, the Director, the EDL, the translation, the validator and
 * the renderer are the production ones, and the assertions are measurements of the finished file —
 * duration from ffprobe, pixels from extracted frames — not readings of a filter string.
 *
 * PRODUCTION STATUS: LOCAL RENDER. What is proven is that the chain produces a correct video from
 * synthetic sources on this machine. It says nothing about provider retrieval, which needs keys.
 */
import { execFile } from "child_process";
import { promisify } from "util";
import * as fs from "fs";
import * as os from "os";
import * as path from "path";
import { afterAll, beforeAll, describe, expect, it } from "vitest";

import {
  buildCinematicSceneInputs,
  type AdoptionFacts,
  type ProductionBeat,
  type SceneFacts,
} from "./cinematicPipelineInputs";
import { formatCinematicGraphics, runCinematicPipeline } from "./cinematicPipeline";
import { renderTimeline } from "./timelineRenderer";
import { resolveFFmpegBin } from "./ffmpegBinary";
import { NON_BLOCKING_ISSUES, formatTimelineIssue, validateTimeline } from "./timelineValidator";
import {
  beatNamedEntitiesByKind,
  extractActionCue,
  extractPersonNamesFromText,
  extractVisualPlacePhrase,
} from "./videoPipeline";
import type { ProjectTimeline } from "./projectTimeline";
import type { Scene } from "./pipeline/types";

const execFileAsync = promisify(execFile);
const FFMPEG = resolveFFmpegBin();

/* ═══════════════════════ the script ═══════════════════════ */

/**
 * Three beats that reach three DIFFERENT planner rules, so no single rule can carry the render:
 * a dated historical event, a named object, and a named company.
 */
const BEATS = [
  "In April 1945 the Battle of Berlin reached the city centre.",
  "He held the pistol in his right hand and said nothing.",
  "Tesla opened a new plant outside Berlin that same decade.",
];

/** One flat colour per beat, so a frame can say which clip it came from. */
const COLOURS = ["red", "green", "blue"];
const BEAT_SEC = 4;

const PRODUCTION_EXTRACTORS = {
  people: (t: string) => extractPersonNamesFromText(t),
  place: (t: string) => extractVisualPlacePhrase(t),
  action: (t: string) => extractActionCue(t),
  namedEntities: (t: string) => beatNamedEntitiesByKind(t),
};

let dir = "";
const media: string[] = [];
let timeline: ProjectTimeline;
let output = "";
let renderSkipped: string[] = [];

async function makeClip(colour: string, out: string): Promise<void> {
  await execFileAsync(FFMPEG, [
    "-y", "-hide_banner", "-loglevel", "error",
    "-f", "lavfi", "-i", `color=c=${colour}:s=1280x720:d=10:r=25`,
    "-c:v", "libx264", "-preset", "ultrafast", "-pix_fmt", "yuv420p", out,
  ]);
}

function beat(index: number, text: string): ProductionBeat {
  return {
    index,
    text,
    searchQuery: "berlin 1945",
    powerWord: "Berlin",
    keywords: ["berlin"],
    holdSec: BEAT_SEC,
    visualDescription: "",
    voiceStartSec: index * BEAT_SEC,
    voiceEndSec: index * BEAT_SEC + BEAT_SEC,
  };
}

function adoption(i: number): AdoptionFacts {
  return {
    provider: "internet_archive",
    providerAssetId: `showcase-${i}`,
    sourceUrl: `https://archive.invalid/${i}.mp4`,
    assetTitle: "Berlin 1945",
    query: "berlin 1945",
  };
}

function sceneFacts(): SceneFacts {
  const beats = BEATS.map((t, i) => beat(i, t));
  const scene: Scene = {
    index: 0,
    text: BEATS.join(" "),
    visualCue: "",
    pexelsQuery: "",
    aiImagePrompt: "",
    duration: BEATS.length * BEAT_SEC,
  };
  return {
    scene,
    beats,
    clips: beats.map((_, i) => ({
      facts: { localPath: media[i]!, durationSec: 10, widthPx: 1280, heightPx: 720 },
      adoption: adoption(i),
    })),
  };
}

/* ═══════════════════════ measuring the finished file ═══════════════════════ */

async function probe(video: string): Promise<{ durationSec: number; width: number; height: number }> {
  const { stdout } = await execFileAsync("ffprobe", [
    "-v", "error", "-select_streams", "v:0",
    "-show_entries", "stream=width,height:format=duration",
    "-of", "default=noprint_wrappers=1:nokey=1", video,
  ]);
  const [w, h, d] = stdout.trim().split("\n").map(Number) as [number, number, number];
  return { width: w, height: h, durationSec: d };
}

type RGB = { r: number; g: number; b: number };

/** The average colour of a frame, which is what says WHICH source clip is on screen. */
async function averageColourAt(video: string, atSec: number): Promise<RGB> {
  const raw = path.join(dir, `frame_${atSec.toFixed(2)}.rgb`);
  await execFileAsync(FFMPEG, [
    "-y", "-hide_banner", "-loglevel", "error",
    "-ss", atSec.toFixed(3), "-i", video,
    "-frames:v", "1", "-vf", "scale=32:18", "-f", "rawvideo", "-pix_fmt", "rgb24", raw,
  ]);
  const buf = fs.readFileSync(raw);
  let r = 0, g = 0, b = 0;
  for (let i = 0; i < buf.length; i += 3) {
    r += buf[i]!; g += buf[i + 1]!; b += buf[i + 2]!;
  }
  const n = buf.length / 3;
  return { r: r / n, g: g / n, b: b / n };
}

const dominant = (c: RGB): "r" | "g" | "b" =>
  c.r >= c.g && c.r >= c.b ? "r" : c.g >= c.b ? "g" : "b";

/* ═══════════════════════ the run ═══════════════════════ */

beforeAll(async () => {
  dir = fs.mkdtempSync(path.join(os.tmpdir(), "r182-showcase-"));
  for (const [i, colour] of COLOURS.entries()) {
    const p = path.join(dir, `src_${i}.mp4`);
    await makeClip(colour, p);
    media.push(p);
  }

  const built = buildCinematicSceneInputs({
    scenes: [sceneFacts()],
    extractors: PRODUCTION_EXTRACTORS,
  });
  expect(built.dropped, `beats dropped: ${built.dropped.join("; ")}`).toEqual([]);

  const result = runCinematicPipeline({ videoId: 182, scenes: built.scenes });
  timeline = result.timeline;
  /** Printed so the run's own graphics verdict is visible in the test log, as production logs it. */
  console.log(formatCinematicGraphics(result));

  output = path.join(dir, "showcase.mp4");
  const rendered = await renderTimeline({
    timeline,
    workDir: path.join(dir, "render"),
    outputPath: output,
    /** The plan's identities map back to the synthetic sources, by provider asset id. */
    resolveMedia: async (clip) => {
      const id = clip.source.providerAssetId ?? "";
      const i = Number(id.replace("showcase-", ""));
      return Number.isFinite(i) ? media[i] ?? null : null;
    },
  });
  renderSkipped = rendered.skipped;
}, 300_000);

afterAll(() => {
  try { fs.rmSync(dir, { recursive: true, force: true }); } catch { /* ignore */ }
});

/* ═══════════════════════ the plan ═══════════════════════ */

describe("R182 — the plan the real route produced", () => {
  it("is a valid timeline by the production validator, with no blocking issue", () => {
    const issues = validateTimeline(timeline).issues;
    /** The same partition production makes: `video_gap` and friends stay advisory by policy. */
    const blocking = issues.filter((i) => !NON_BLOCKING_ISSUES.has(i.code));
    expect(blocking, blocking.map(formatTimelineIssue).join("\n")).toEqual([]);
  });

  it("has one clip per beat, in beat order, covering the whole video", () => {
    const track = timeline.tracks.find((t) => t.kind === "VIDEO");
    const clips = track && track.kind === "VIDEO" ? track.clips : [];
    expect(clips).toHaveLength(BEATS.length);
    expect(clips.map((c) => c.timelineStart)).toEqual([0, 4, 8]);
    expect(timeline.durationSec).toBeCloseTo(BEATS.length * BEAT_SEC, 1);
  });

  /** The cinematic decisions are IN the document — that is what makes them renderable at all. */
  it("carries camera, captions and graphics rather than a bare cut list", () => {
    const video = timeline.tracks.find((t) => t.kind === "VIDEO");
    const clips = video && video.kind === "VIDEO" ? video.clips : [];
    expect(clips.some((c) => c.camera), "no camera move survived into the timeline").toBe(true);

    const graphics = timeline.tracks.find((t) => t.kind === "GRAPHICS");
    expect(graphics && graphics.kind === "GRAPHICS" ? graphics.graphics.length : 0).toBeGreaterThan(0);

    const captionCount = timeline.tracks
      .filter((t) => t.kind === "CAPTIONS" || t.kind === "TEXT")
      .reduce((n, t) => n + (t.kind === "CAPTIONS" ? t.captions.length : t.kind === "TEXT" ? t.texts.length : 0), 0);
    expect(captionCount).toBeGreaterThan(0);
  });

  /** §11 — the same script plans the same video, every time. */
  it("is deterministic: the same beats plan the same document", () => {
    const again = runCinematicPipeline({
      videoId: 182,
      scenes: buildCinematicSceneInputs({ scenes: [sceneFacts()], extractors: PRODUCTION_EXTRACTORS }).scenes,
    }).timeline;
    const content = (t: ProjectTimeline) => JSON.stringify({ ...t, version: 0, createdAt: "" });
    expect(content(again)).toBe(content(timeline));
  });
});

/* ═══════════════════════ the pixels ═══════════════════════ */

describe("R182 — the video the renderer actually produced", () => {
  it("exists and is a playable file", async () => {
    expect(fs.existsSync(output)).toBe(true);
    expect(fs.statSync(output).size).toBeGreaterThan(10_000);
    const meta = await probe(output);
    expect(meta.width).toBe(timeline.format.widthPx);
    expect(meta.height).toBe(timeline.format.heightPx);
  });

  /**
   * ── The defect this showcase found, and why the assertion is what it is ────────────────────
   *
   * The plan says 12.00s. The file is 10.70s. Neither number is wrong on its own: a crossfade
   * overlaps its two neighbours, so two 0.65s dissolves take 1.30s out of the running total.
   *
   * What was wrong is that NOTHING SAID SO. `buildTransitionGraph` already returns the true length
   * as `totalSec` and the renderer discarded it, so a timeline whose VOICE track is 12s long
   * rendered a picture ending 1.3s before the narration and reported success.
   *
   * The renderer now reports it. This asserts the two halves that can be settled here: the file's
   * length matches the sum of the segments MINUS the overlaps, and the discrepancy is named. What
   * the product should do about it — extend the last clip, or plan the clips accounting for the
   * overlap — is an editorial decision that needs somebody to look at a frame, and this round does
   * not make it silently.
   */
  it("is exactly as long as the plan minus the transition overlaps, and says so", async () => {
    const meta = await probe(output);
    const report = renderSkipped.find((s) => s.startsWith("transition_overlap:"));
    if (!report) {
      /** No transition was rendered, so the picture must be the full planned length. */
      expect(meta.durationSec).toBeGreaterThan(timeline.durationSec - 0.2);
      expect(meta.durationSec).toBeLessThan(timeline.durationSec + 0.2);
      return;
    }
    const shortfall = Number(/by ([\d.]+)s in total/.exec(report)?.[1] ?? NaN);
    expect(Number.isFinite(shortfall), report).toBe(true);
    expect(meta.durationSec).toBeGreaterThan(timeline.durationSec - shortfall - 0.2);
    expect(meta.durationSec).toBeLessThan(timeline.durationSec - shortfall + 0.2);
    /** And the shortfall is real, not a rounding artefact — this is the defect being pinned. */
    expect(shortfall).toBeGreaterThan(0.04);
  });

  /**
   * Each beat's own source is on screen during that beat. Sampled at the MIDDLE of each slot, away
   * from any transition, so a dissolve at the boundary cannot decide the answer.
   */
  it("shows each beat's own clip during that beat", async () => {
    for (const [i, expected] of (["r", "g", "b"] as const).entries()) {
      const at = i * BEAT_SEC + BEAT_SEC / 2;
      const colour = await averageColourAt(output, at);
      expect(dominant(colour), `at ${at}s the frame is not clip ${i}`).toBe(expected);
    }
  });

  /**
   * §2 — nothing disappears silently. Whatever the renderer could not do is REPORTED, and on this
   * machine the report is allowed to be non-empty (there may be no browser for the overlay); what
   * is not allowed is a dropped clip, which would be a hole in the video.
   */
  it("reports what it skipped, and skipped no clip", () => {
    for (const line of renderSkipped) {
      expect(line, `a clip was dropped: ${line}`).not.toContain("source could not be recovered");
    }
  });
});
