/**
 * World geography slugs for archive geo-blocking and beat matching.
 * NL + US have dedicated lists; everything else is FOREIGN.
 */

function dedupe(slugs: string[]): string[] {
  return [...new Set(slugs.map((s) => s.toLowerCase().trim()).filter((s) => s.length >= 2))];
}

/** Netherlands — country, demonyms, provinces, major cities. */
export const NL_GEO_SLUGS = dedupe([
  "netherlands",
  "holland",
  "dutch",
  "nederland",
  "nederlands",
  "nederlandse",
  "amsterdam",
  "rotterdam",
  "the hague",
  "den haag",
  "utrecht",
  "eindhoven",
  "groningen",
  "tilburg",
  "almere",
  "breda",
  "nijmegen",
  "enschede",
  "haarlem",
  "arnhem",
  "zaanstad",
  "amersfoort",
  "apeldoorn",
  "s-hertogenbosch",
  "'s-hertogenbosch",
  "maastricht",
  "leiden",
  "dordrecht",
  "zoetermeer",
  "zwolle",
  "deventer",
  "delft",
  "leeuwarden",
  "alkmaar",
  "hilversum",
  "amstelveen",
  "purmerend",
  "schiedam",
  "spijkenisse",
  "helmond",
  "venlo",
  "ede",
  "canal",
  "gracht",
  "fietspad",
  "polder",
  "windmill",
  "molen",
  "noord-brabant",
  "brabant",
  "friesland",
  "gelderland",
  "limburg",
  "overijssel",
  "zeeland",
  "flevoland",
  "drenthe",
]);

/** United States — country, demonyms, states, territories, major cities. */
export const US_GEO_SLUGS = dedupe([
  "united states",
  "usa",
  "u.s.",
  "u.s.a.",
  "america",
  "american",
  "us city",
  "american city",
  "suburban",
  "suburb",
  "suburbs",
  // States + DC
  "alabama",
  "alaska",
  "arizona",
  "arkansas",
  "california",
  "colorado",
  "connecticut",
  "delaware",
  "florida",
  "georgia",
  "hawaii",
  "idaho",
  "illinois",
  "indiana",
  "iowa",
  "kansas",
  "kentucky",
  "louisiana",
  "maine",
  "maryland",
  "massachusetts",
  "michigan",
  "minnesota",
  "mississippi",
  "missouri",
  "montana",
  "nebraska",
  "nevada",
  "new hampshire",
  "new jersey",
  "new mexico",
  "new york",
  "north carolina",
  "north dakota",
  "ohio",
  "oklahoma",
  "oregon",
  "pennsylvania",
  "rhode island",
  "south carolina",
  "south dakota",
  "tennessee",
  "texas",
  "utah",
  "vermont",
  "virginia",
  "washington",
  "west virginia",
  "wisconsin",
  "wyoming",
  "district of columbia",
  "washington dc",
  "washington d.c.",
  "puerto rico",
  "guam",
  // Major cities
  "new york city",
  "nyc",
  "manhattan",
  "brooklyn",
  "queens",
  "bronx",
  "staten island",
  "los angeles",
  "chicago",
  "houston",
  "phoenix",
  "philadelphia",
  "san antonio",
  "san diego",
  "dallas",
  "san jose",
  "austin",
  "jacksonville",
  "fort worth",
  "columbus",
  "charlotte",
  "san francisco",
  "indianapolis",
  "seattle",
  "denver",
  "boston",
  "nashville",
  "detroit",
  "portland",
  "las vegas",
  "memphis",
  "louisville",
  "baltimore",
  "milwaukee",
  "albuquerque",
  "tucson",
  "fresno",
  "sacramento",
  "kansas city",
  "mesa",
  "atlanta",
  "omaha",
  "colorado springs",
  "raleigh",
  "miami",
  "long beach",
  "virginia beach",
  "oakland",
  "minneapolis",
  "tampa",
  "tulsa",
  "arlington",
  "new orleans",
  "wichita",
  "cleveland",
  "bakersfield",
  "aurora",
  "anaheim",
  "honolulu",
  "santa ana",
  "riverside",
  "corpus christi",
  "lexington",
  "stockton",
  "henderson",
  "saint paul",
  "st paul",
  "st. paul",
  "st louis",
  "st. louis",
  "cincinnati",
  "pittsburgh",
  "anchorage",
  "greensboro",
  "plano",
  "lincoln",
  "orlando",
  "irvine",
  "newark",
  "durham",
  "chula vista",
  "toledo",
  "fort wayne",
  "st petersburg",
  "laredo",
  "jersey city",
  "chandler",
  "madison",
  "lubbock",
  "scottsdale",
  "reno",
  "buffalo",
  "gilbert",
  "glendale",
  "north las vegas",
  "winston-salem",
  "chesapeake",
  "norfolk",
  "fremont",
  "garland",
  "irving",
  "hialeah",
  "richmond",
  "boise",
  "spokane",
  "baton rouge",
  "tacoma",
  "san bernardino",
  "modesto",
  "fontana",
  "des moines",
  "moreno valley",
  "fayetteville",
  "rochester",
  "yonkers",
  "huntington beach",
  "salt lake city",
  "grand rapids",
  "amarillo",
  "mobile",
  "little rock",
  "providence",
  "tallahassee",
  "huntsville",
  "knoxville",
  "worcester",
  "newport news",
  "brownsville",
  "overland park",
  "santa clarita",
  "grand prairie",
  "peoria",
  "cape coral",
  "springfield",
  "sioux falls",
  "port st lucie",
  "chattanooga",
  "tempe",
  "eugene",
  "salem",
  "fort lauderdale",
  "oak park",
  "bank of america stadium",
  "empire state",
]);

/** Rest of world — countries, demonyms, and major cities (excludes NL/US lists). */
export const FOREIGN_GEO_SLUGS = dedupe([
  // Europe
  "albania", "albanian", "tirana",
  "andorra",
  "armenia", "armenian", "yerevan",
  "austria", "austrian", "vienna", "wien", "salzburg", "innsbruck", "graz",
  "azerbaijan", "baku",
  "belarus", "belarusian", "minsk",
  "belgium", "belgian", "brussels", "bruxelles", "antwerp", "antwerpen", "ghent", "gent", "bruges", "brugge",
  "bosnia", "bosnian", "sarajevo", "herzegovina",
  "bulgaria", "bulgarian", "sofia",
  "croatia", "croatian", "zagreb", "split", "dubrovnik",
  "cyprus", "nicosia", "limassol",
  "czech republic", "czechia", "czech", "prague", "praha", "brno",
  "denmark", "danish", "copenhagen", "kobenhavn", "aarhus", "odense",
  "estonia", "estonian", "tallinn",
  "finland", "finnish", "helsinki", "tampere", "turku",
  "france", "french", "paris", "parijs", "lyon", "marseille", "toulouse", "nice", "nantes", "strasbourg", "bordeaux", "lille",
  "georgia", "tbilisi",
  "germany", "german", "deutschland", "deutsche", "berlin", "berlijn", "munich", "munchen", "münchen", "hamburg", "frankfurt", "cologne", "koln", "köln", "stuttgart", "dusseldorf", "düsseldorf", "dortmund", "essen", "leipzig", "bremen", "dresden", "hanover", "nuremberg", "nürnberg",
  "greece", "greek", "athens", "thessaloniki",
  "hungary", "hungarian", "budapest",
  "iceland", "icelandic", "reykjavik",
  "ireland", "irish", "dublin", "cork", "galway",
  "italy", "italian", "italie", "italië", "rome", "roma", "milan", "milano", "naples", "napoli", "turin", "torino", "florence", "firenze", "venice", "venezia", "bologna",
  "kosovo", "pristina",
  "latvia", "latvian", "riga",
  "liechtenstein", "vaduz",
  "lithuania", "lithuanian", "vilnius", "kaunas",
  "luxembourg", "luxembourgish",
  "malta", "valletta",
  "moldova", "chisinau",
  "monaco", "monte carlo",
  "montenegro", "podgorica",
  "north macedonia", "macedonia", "skopje",
  "norway", "norwegian", "oslo", "bergen", "trondheim", "stavanger",
  "poland", "polish", "polen", "warsaw", "warschau", "krakow", "kraków", "wroclaw", "wrocław", "gdansk", "gdańsk", "poznan", "poznań", "lodz", "łódź",
  "portugal", "portuguese", "lisbon", "lisboa", "porto",
  "romania", "romanian", "bucharest", "bucuresti", "cluj",
  "russia", "russian", "rusland", "moscow", "moskou", "saint petersburg", "st petersburg", "novosibirsk", "yekaterinburg", "kazan", "soviet", "sovjet", "urss", "ussr",
  "san marino",
  "serbia", "serbian", "belgrade", "beograd", "novi sad",
  "slovakia", "slovak", "bratislava",
  "slovenia", "slovenian", "ljubljana",
  "spain", "spanish", "madrid", "barcelona", "valencia", "seville", "sevilla", "zaragoza", "malaga", "málaga", "bilbao",
  "sweden", "swedish", "stockholm", "gothenburg", "goteborg", "göteborg", "malmo", "malmö",
  "switzerland", "swiss", "zurich", "zürich", "geneva", "genève", "basel", "bern", "lausanne",
  "turkey", "turkish", "turkiye", "istanbul", "ankara", "izmir",
  "ukraine", "ukrainian", "kyiv", "kiev", "kharkiv", "odesa", "odessa", "lviv",
  "united kingdom", "uk", "britain", "british", "england", "english", "scotland", "scottish", "wales", "welsh", "northern ireland",
  "london", "birmingham", "manchester", "glasgow", "liverpool", "leeds", "sheffield", "edinburgh", "bristol", "cardiff", "belfast",
  "vatican",
  // Americas (non-US)
  "antigua", "argentina", "argentine", "buenos aires", "cordoba", "rosario",
  "bahamas", "nassau",
  "barbados", "bridgetown",
  "belize",
  "bolivia", "la paz", "santa cruz",
  "brazil", "brasil", "brazilian", "sao paulo", "são paulo", "rio de janeiro", "brasilia", "brasília", "salvador", "fortaleza", "belo horizonte", "manaus", "curitiba",
  "canada", "canadian", "toronto", "montreal", "montréal", "vancouver", "calgary", "edmonton", "ottawa", "winnipeg", "quebec", "québec", "hamilton", "kitchener",
  "ontario", "scarborough", "etobicoke", "north york", "mississauga",
  "chile", "chilean", "santiago", "valparaiso",
  "colombia", "colombian", "bogota", "bogotá", "medellin", "medellín", "cali", "cartagena",
  "costa rica", "san jose",
  "cuba", "havana", "la habana",
  "dominican republic", "santo domingo",
  "ecuador", "quito", "guayaquil",
  "el salvador", "san salvador",
  "guatemala", "guatemala city",
  "guyana", "georgetown",
  "haiti", "port-au-prince",
  "honduras", "tegucigalpa",
  "jamaica", "kingston",
  "mexico", "mexican", "mexico city", "ciudad de mexico", "guadalajara", "monterrey", "puebla", "tijuana", "cancun",
  "nicaragua", "managua",
  "panama", "panama city",
  "paraguay", "asuncion", "asunción",
  "peru", "peruvian", "lima", "arequipa", "cusco", "cuzco",
  "suriname", "paramaribo",
  "trinidad", "tobago", "port of spain",
  "uruguay", "montevideo",
  "venezuela", "caracas", "maracaibo",
  // Africa
  "algeria", "algerian", "algiers",
  "angola", "luanda",
  "benin", "porto-novo",
  "botswana", "gaborone",
  "burkina faso", "ouagadougou",
  "burundi", "bujumbura",
  "cameroon", "yaounde", "douala",
  "cape verde",
  "central african republic", "bangui",
  "chad", "ndjamena",
  "congo", "kinshasa", "brazzaville",
  "djibouti",
  "egypt", "egyptian", "cairo", "alexandria", "giza",
  "eritrea", "asmara",
  "eswatini", "swaziland", "mbabane",
  "ethiopia", "ethiopian", "addis ababa",
  "gabon", "libreville",
  "gambia", "banjul",
  "ghana", "accra", "kumasi",
  "guinea", "conakry",
  "ivory coast", "cote d'ivoire", "abidjan",
  "kenya", "kenyan", "nairobi", "mombasa",
  "lesotho", "maseru",
  "liberia", "monrovia",
  "libya", "tripoli", "benghazi",
  "madagascar", "antananarivo",
  "malawi", "lilongwe",
  "mali", "bamako",
  "mauritania", "nouakchott",
  "mauritius", "port louis",
  "morocco", "moroccan", "casablanca", "rabat", "marrakech", "fes", "fez", "tangier",
  "mozambique", "maputo",
  "namibia", "windhoek",
  "niger", "niamey",
  "nigeria", "nigerian", "lagos", "abuja", "kano", "ibadan",
  "rwanda", "kigali",
  "senegal", "dakar",
  "seychelles", "victoria",
  "sierra leone", "freetown",
  "somalia", "mogadishu",
  "south africa", "south african", "johannesburg", "cape town", "durban", "pretoria", "soweto",
  "south sudan", "juba",
  "sudan", "khartoum",
  "tanzania", "dar es salaam", "dodoma",
  "togo", "lome",
  "tunisia", "tunis",
  "uganda", "kampala",
  "zambia", "lusaka",
  "zimbabwe", "harare",
  // Middle East
  "afghanistan", "kabul", "kandahar",
  "bahrain", "manama",
  "iran", "iranian", "tehran", "isfahan", "mashhad", "shiraz",
  "iraq", "iraqi", "baghdad", "basra", "mosul", "erbil",
  "israel", "israeli", "tel aviv", "jerusalem", "haifa",
  "jordan", "amman",
  "kuwait", "kuwait city",
  "lebanon", "lebanese", "beirut",
  "oman", "muscat",
  "palestine", "palestinian", "gaza", "ramallah", "west bank",
  "qatar", "doha",
  "saudi arabia", "saudi", "riyadh", "jeddah", "mecca", "makkah", "medina",
  "syria", "syrian", "damascus", "aleppo",
  "united arab emirates", "uae", "dubai", "abu dhabi", "sharjah",
  "yemen", "sanaa", "aden",
  // Asia
  "armenia", "yerevan",
  "bangladesh", "bangladeshi", "dhaka", "chittagong",
  "bhutan", "thimphu",
  "brunei", "bandar seri begawan",
  "cambodia", "phnom penh", "siem reap",
  "china", "chinese", "beijing", "peking", "shanghai", "guangzhou", "shenzhen", "chengdu", "chongqing", "wuhan", "xian", "xi'an", "hangzhou", "nanjing", "tianjin", "hong kong",
  "india", "indian", "mumbai", "bombay", "delhi", "new delhi", "bangalore", "bengaluru", "hyderabad", "chennai", "kolkata", "calcutta", "ahmedabad", "pune", "jaipur",
  "indonesia", "indonesian", "jakarta", "surabaya", "bandung", "bali", "denpasar",
  "japan", "japanese", "tokyo", "osaka", "yokohama", "nagoya", "sapporo", "fukuoka", "kobe", "kyoto", "hiroshima",
  "kazakhstan", "almaty", "astana", "nur-sultan",
  "kyrgyzstan", "bishkek",
  "laos", "vientiane",
  "malaysia", "malaysian", "kuala lumpur", "george town", "johor bahru",
  "maldives", "male",
  "mongolia", "ulaanbaatar",
  "myanmar", "burma", "yangon", "rangoon", "naypyidaw",
  "nepal", "kathmandu",
  "north korea", "pyongyang",
  "pakistan", "pakistani", "karachi", "lahore", "islamabad", "faisalabad",
  "philippines", "filipino", "manila", "quezon city", "davao", "cebu",
  "singapore", "singaporean",
  "south korea", "korean", "seoul", "busan", "incheon", "daegu",
  "sri lanka", "colombo",
  "taiwan", "taiwanese", "taipei", "kaohsiung",
  "tajikistan", "dushanbe",
  "thailand", "thai", "bangkok", "chiang mai", "phuket",
  "timor-leste", "east timor", "dili",
  "turkmenistan", "ashgabat",
  "uzbekistan", "tashkent", "samarkand",
  "vietnam", "vietnamese", "hanoi", "ho chi minh", "saigon", "da nang",
  // Oceania
  "australia", "australian", "sydney", "melbourne", "brisbane", "perth", "adelaide", "canberra", "gold coast",
  "fiji", "suva",
  "new zealand", "auckland", "wellington", "christchurch",
  "papua new guinea", "port moresby",
  "samoa", "apia",
  "tonga",
  // Generic regions
  "europe", "european", "europa",
  "asia", "asian",
  "africa", "african",
  "latin america", "south america", "central america",
  "middle east",
  "caribbean",
  "scandinavia", "scandinavian", "nordic",
  "balkans", "balkan",
  "maghreb",
  "sub-saharan",
]);

/** All non-NL place markers for segment-lock QA (US + foreign). */
export const NON_NL_GEO_SLUGS = dedupe([...US_GEO_SLUGS, ...FOREIGN_GEO_SLUGS]);

/** Combined list for beat-text geo extraction. */
export const ALL_GEO_SLUGS = dedupe([...NL_GEO_SLUGS, ...US_GEO_SLUGS, ...FOREIGN_GEO_SLUGS]);

const SHORT_GEO_SLUGS = new Set(
  ALL_GEO_SLUGS.filter((s) => s.length <= 3 || s === "uk" || s === "uae" || s === "usa")
);

/** Match geo slug in narration — word boundaries for short tokens (us, uk, uae). */
export function beatTextMentionsGeoSlug(beatText: string, slug: string): boolean {
  const lower = beatText.toLowerCase();
  if (SHORT_GEO_SLUGS.has(slug)) {
    const escaped = slug.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
    return new RegExp(`\\b${escaped}\\b`, "i").test(lower);
  }
  return lower.includes(slug);
}

export function hayHasGeoMarker(hay: string, markers: readonly string[]): boolean {
  const lower = hay.toLowerCase();
  return markers.some((m) => lower.includes(m));
}

export function assetHayHasGeoMarkers(
  asset: Pick<{ title?: string | null; tags?: string[] | null }, "title" | "tags">,
  markers: readonly string[]
): boolean {
  const hay = `${(asset.title ?? "").toLowerCase()} ${(asset.tags ?? []).join(" ").toLowerCase()}`;
  return hayHasGeoMarker(hay, markers);
}

export function assetHasNlMarkers(
  asset: Pick<{ title?: string | null; tags?: string[] | null }, "title" | "tags">
): boolean {
  return assetHayHasGeoMarkers(asset, NL_GEO_SLUGS);
}

export function assetHasUsMarkers(
  asset: Pick<{ title?: string | null; tags?: string[] | null }, "title" | "tags">
): boolean {
  return assetHayHasGeoMarkers(asset, US_GEO_SLUGS);
}

export function assetHasForeignMarkers(
  asset: Pick<{ title?: string | null; tags?: string[] | null }, "title" | "tags">
): boolean {
  return assetHayHasGeoMarkers(asset, FOREIGN_GEO_SLUGS);
}
