/** Visual Matching Engine V2 — BeatSelectionTrace types.
 *
 *  Pure storage layer. No pipeline logic — only receives SelectorTrace from the Selector
 *  and persists it. Imports nothing from retrieval, ranking, vision, or CLIP modules. */
import type { SelectorTrace } from "../types";
import { PROMPT_VERSION } from "../visionPromptBuilder";

// ─── Version constants ──────────────────────────────────────────────────────────

export const TRACE_VERSION = "1";
export const SELECTOR_VERSION = "1";
export const VISION_VERSION = "1";
export const RANKING_VERSION = "1";
export const SCHEMA_VERSION = "1.0";
export const ENGINE_VERSION = "v2";
/** Identifies the pipeline that produced this trace. Allows traces from different pipeline
 *  variants (v1, v2, v2.1, experimental-v3) to be filtered without parsing engineVersion. */
export const PIPELINE_VERSION = "visual-matching-v2";

// Re-export for convenience so DatabaseTraceStore does not need to import visionPromptBuilder.
export { PROMPT_VERSION };

// ─── Trace context (caller-supplied index hints) ────────────────────────────────

/** Optional context passed alongside a SelectorTrace to enrich index columns that are
 *  not derivable from the trace itself (e.g. videoId is owned by the video pipeline,
 *  not the selector). All fields are optional; absent fields produce NULL in the DB. */
export type TraceContext = {
  videoId?: string;
  /** UUID of the enclosing pipeline run — required for VideoQualityReport to join
   *  beat traces to their run without relying on time-window heuristics. */
  pipelineRunId?: string;
};

// ─── Trace metadata (storage-layer generated) ──────────────────────────────────

/** Fields generated by the store at write time, not by the selector or pipeline.
 *  Not reconstructed from payload — stored as separate columns for fast queries. */
export type TraceMetadata = {
  traceId: string;
  schemaVersion: string;
  engineVersion: string;
  pipelineVersion: string;
  createdAt: string;  // ISO timestamp — when the trace was persisted (not when selection ran)
  host: string;
  workerId: string;
};

// ─── Versioned + metadata wrapper ──────────────────────────────────────────────

export type VersionedSelectorTrace = SelectorTrace & TraceMetadata & {
  traceVersion: string;
  selectorVersion: string;
  visionVersion: string;
  rankingVersion: string;
  promptVersion: string;
};

// ─── Serializer interface ───────────────────────────────────────────────────────

export interface TraceSerializer {
  serialize(trace: VersionedSelectorTrace): string;
  contentType: string;
}

export class JsonTraceSerializer implements TraceSerializer {
  readonly contentType = "application/json";
  serialize(trace: VersionedSelectorTrace): string {
    return JSON.stringify(trace);
  }
}

/** Registered for future activation — not yet usable. Swap into DatabaseTraceStore
 *  without touching any other file when gzip compression is needed. */
export class GzipJsonSerializer implements TraceSerializer {
  readonly contentType = "application/json+gzip";
  serialize(_trace: VersionedSelectorTrace): string {
    throw new Error("GzipJsonSerializer: not yet implemented");
  }
}

/** Registered for future activation — not yet usable. */
export class MsgPackSerializer implements TraceSerializer {
  readonly contentType = "application/msgpack";
  serialize(_trace: VersionedSelectorTrace): string {
    throw new Error("MsgPackSerializer: not yet implemented");
  }
}

// ─── Retention policy ──────────────────────────────────────────────────────────

/** Extensibility point for retention enforcement. No implementation is shipped — the
 *  store controls retention at query time (e.g. a nightly cron deletes rows where
 *  startedAt < NOW() - INTERVAL). Implement and inject when per-trace rules are needed. */
export interface TraceRetentionPolicy {
  shouldDelete(trace: VersionedSelectorTrace): boolean;
  shouldArchive(trace: VersionedSelectorTrace): boolean;
}

// ─── Store interface ────────────────────────────────────────────────────────────

/** The sole contract for persisting a SelectorTrace. Implementations: DatabaseTraceStore,
 *  MemoryTraceStore (tests), NullTraceStore (feature flag off). A failed save MUST NOT
 *  propagate — video production continues regardless of trace storage outcome. */
export interface BeatSelectionTraceStore {
  save(trace: SelectorTrace, context?: TraceContext): Promise<void>;
}
