/**
 * §42 — A FEATURE-LENGTH RENDER, THROUGH THE PRODUCTION CHAIN, MEASURED.
 *
 * ── Why this exists ─────────────────────────────────────────────────────────────────────────
 *
 * The longest render anywhere in the test suite is R182's TWELVE SECONDS. Everything this codebase
 * knows about its own renderer it learned from three-shot films. The failures that matter for an
 * eight-to-ten minute documentary — argv length, filter-graph size, memory, wall clock, and drift
 * between the planned duration and the file's — do not exist at three shots and are the only ones
 * that decide whether a production render finishes at all.
 *
 * So this plans and renders a film of the length the product actually sells, through
 * `buildCinematicSceneInputs` → `runCinematicPipeline` → `renderTimeline`: the production planner,
 * the production Director, the production EDL translation, the production renderer.
 *
 * ── What is synthetic, and what that costs the claim ────────────────────────────────────────
 *
 * The MEDIA is synthetic — flat-coloured clips with a tone, generated by ffmpeg — because this
 * environment has no provider credentials. The narration is pink noise of the right length rather
 * than speech.
 *
 * So this proves nothing whatsoever about retrieval, relevance, or whether the film is any good. It
 * proves the half that is ours: that the chain from a long script to a finished, playable,
 * correctly-timed MP4 holds at production length. Read every number below as LOCAL RENDER, not as
 * production validation.
 *
 * ── Running it ──────────────────────────────────────────────────────────────────────────────
 *
 *     npx tsx scripts/featureLengthRender.ts
 *     TARGET_MIN=3 npx tsx scripts/featureLengthRender.ts     # a quicker pass
 *
 * It is a script rather than a test on purpose: at nine minutes of output it costs minutes of CPU,
 * and a suite everyone runs is the wrong place for that. Nothing in it is skipped or stubbed.
 */
import { describe, expect, it } from "vitest";
import { execFile } from "child_process";
import { promisify } from "util";
import * as fs from "fs";
import * as os from "os";
import * as path from "path";

import {
  buildCinematicSceneInputs,
  type AdoptionFacts,
  type ProductionBeat,
  type SceneFacts,
} from "../server/cinematicPipelineInputs";
import { runCinematicPipeline } from "../server/cinematicPipeline";
import { renderTimeline } from "../server/timelineRenderer";
import { resolveFFmpegBin } from "../server/ffmpegBinary";
import { checkFileAvSync } from "../server/avSyncCheck";
import { NON_BLOCKING_ISSUES, formatTimelineIssue, validateTimeline } from "../server/timelineValidator";
import {
  beatNamedEntitiesByKind,
  extractActionCue,
  extractPersonNamesFromText,
  extractVisualPlacePhrase,
} from "../server/videoPipeline";
import type { Scene } from "../server/pipeline/types";

const execFileAsync = promisify(execFile);
const FFMPEG = resolveFFmpegBin();
const FFPROBE = process.env.FFPROBE_PATH || "ffprobe";

const TARGET_MIN = Number(process.env.TARGET_MIN ?? "9");
const BEAT_SEC = Number(process.env.BEAT_SEC ?? "3.4");
const BEATS_PER_SCENE = 9;
const TOTAL_BEATS = Math.max(BEATS_PER_SCENE, Math.round((TARGET_MIN * 60) / BEAT_SEC));
const SCENES = Math.ceil(TOTAL_BEATS / BEATS_PER_SCENE);
/** Distinct source files, reused across beats — a real render also re-uses a provider's assets. */
const POOL = 12;

/**
 * Sentence shapes, not a subject.
 *
 * The planner branches on what it can extract — a date, a person, a place, an action, a named
 * organisation, or nothing at all — so the script has to reach every branch or the render only
 * proves the one rule it happened to hit. The nouns are filled in per beat so no two beats are
 * identical and the duplicate-penalty paths are live.
 */
const SHAPES: Array<(n: number) => string> = [
  (n) => `In March 19${40 + (n % 50)} the harbour at Kalmar was closed for the winter.`,
  (n) => `Anna Lindqvist signed the ${n}th register that morning and said nothing.`,
  (n) => `The delegation walked from the station to the old customs house.`,
  (n) => `Nordvik Shipping opened a second yard outside the town that year.`,
  (n) => `He turned the key ${n} times before the lock finally gave.`,
  (n) => `Nobody recorded what happened between the ${n}th and the ${n + 1}th.`,
  (n) => `By the summer of 19${50 + (n % 40)} the ledgers had been moved twice.`,
  (n) => `The photograph shows ${n} figures on the quay, none of them named.`,
  (n) => `Rain had been falling on the roof for most of the afternoon.`,
];

const COLOURS = [
  "0x1b3a4b", "0x3d2b1f", "0x4a4a2f", "0x2f4a3d", "0x4b1b2f", "0x1f2b3d",
  "0x5a3a1b", "0x2a2a2a", "0x3a1b4b", "0x1b4b3a", "0x4b4b1b", "0x2b1b1b",
];

const PRODUCTION_EXTRACTORS = {
  people: (t: string) => extractPersonNamesFromText(t),
  place: (t: string) => extractVisualPlacePhrase(t),
  action: (t: string) => extractActionCue(t),
  namedEntities: (t: string) => beatNamedEntitiesByKind(t),
};

const media: string[] = [];

/**
 * A narration track of the right length.
 *
 * Pink noise rather than speech, because there is no TTS here — and it is supplied because the
 * pipeline always supplies one. A render with no voice track exercises none of the mix, and the
 * audio half of a documentary renderer is exactly what a long render is here to stress.
 */
async function makeVoice(out: string, sec: number): Promise<void> {
  await execFileAsync(FFMPEG, [
    "-y", "-hide_banner", "-loglevel", "error",
    "-f", "lavfi", "-i", `anoisesrc=d=${sec}:c=pink:a=0.10`,
    "-ar", "48000", "-c:a", "aac", out,
  ]);
}

async function makeSource(colour: string, out: string, sec: number): Promise<void> {
  await execFileAsync(FFMPEG, [
    "-y", "-hide_banner", "-loglevel", "error",
    "-f", "lavfi", "-i", `color=c=${colour}:s=1280x720:d=${sec}:r=25`,
    "-c:v", "libx264", "-preset", "ultrafast", "-pix_fmt", "yuv420p", out,
  ]);
}

function beatText(globalIndex: number): string {
  return SHAPES[globalIndex % SHAPES.length]!(globalIndex + 1);
}

function beat(sceneIndex: number, indexInScene: number): ProductionBeat {
  const g = sceneIndex * BEATS_PER_SCENE + indexInScene;
  /**
   * SCENE-LOCAL, not global.
   *
   * `buildCinematicSceneInputs` lays a beat out from its scene's own start and `edlToTimeline` adds
   * `sceneOffsetSec` afterwards. Handing it global times offsets every beat twice: the first run of
   * this harness planned 1060.80s of picture for 540.60s of narration, which is the fixture being
   * wrong rather than the planner.
   */
  const start = indexInScene * BEAT_SEC;
  return {
    index: indexInScene,
    text: beatText(g),
    searchQuery: `archive shot ${g}`,
    powerWord: "harbour",
    keywords: ["harbour", "town"],
    holdSec: BEAT_SEC,
    visualDescription: "",
    voiceStartSec: +start.toFixed(3),
    voiceEndSec: +(start + BEAT_SEC).toFixed(3),
  };
}

function adoption(g: number): AdoptionFacts {
  return {
    provider: "internet_archive",
    providerAssetId: `feat-${g}`,
    sourceUrl: `https://archive.invalid/${g}.mp4`,
    assetTitle: `Harbour reel ${g}`,
    query: `archive shot ${g}`,
  };
}

function sceneFacts(sceneIndex: number): SceneFacts {
  const count = Math.min(BEATS_PER_SCENE, TOTAL_BEATS - sceneIndex * BEATS_PER_SCENE);
  const beats = Array.from({ length: count }, (_, i) => beat(sceneIndex, i));
  const scene: Scene = {
    index: sceneIndex,
    text: beats.map((b) => b.text).join(" "),
    visualCue: "",
    pexelsQuery: "",
    aiImagePrompt: "",
    duration: count * BEAT_SEC,
  };
  return {
    scene,
    beats,
    clips: beats.map((_, i) => {
      const g = sceneIndex * BEATS_PER_SCENE + i;
      return {
        facts: { localPath: media[g % POOL]!, durationSec: 12, widthPx: 1280, heightPx: 720 },
        adoption: adoption(g),
      };
    }),
  };
}

async function probe(file: string) {
  const { stdout } = await execFileAsync(FFPROBE, [
    "-v", "error",
    "-show_entries", "format=duration,size",
    "-show_entries", "stream=codec_type,width,height,r_frame_rate",
    "-of", "json", file,
  ]);
  return JSON.parse(stdout) as {
    format?: { duration?: string; size?: string };
    streams?: Array<{ codec_type?: string; width?: number; height?: number; r_frame_rate?: string }>;
  };
}

type Measured = {
  blocking: string[];
  blockingDetail: string;
  plannedClips: number;
  clipsRendered: number;
  plannedSec: number;
  fileSec: number;
  fps: number;
  avFindings: string[];
};

async function main(): Promise<Measured> {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), "featurelen-"));
  const t0 = Date.now();
  console.log(
    `[§42] target=${TARGET_MIN}min beats=${TOTAL_BEATS} scenes=${SCENES} ` +
      `beatSec=${BEAT_SEC} sourcePool=${POOL}`
  );

  for (let i = 0; i < POOL; i++) {
    const p = path.join(dir, `src_${i}.mp4`);
    await makeSource(COLOURS[i % COLOURS.length]!, p, 14);
    media.push(p);
  }
  const voicePath = path.join(dir, "voice.m4a");
  await makeVoice(voicePath, TOTAL_BEATS * BEAT_SEC);
  console.log(
    `[§42] ${POOL} synthetic sources + ${(TOTAL_BEATS * BEAT_SEC).toFixed(1)}s narration ` +
      `in ${((Date.now() - t0) / 1000).toFixed(1)}s`
  );

  const tPlan = Date.now();
  const built = buildCinematicSceneInputs({
    scenes: Array.from({ length: SCENES }, (_, s) => sceneFacts(s)),
    extractors: PRODUCTION_EXTRACTORS,
    sceneOffsetsSec: Array.from({ length: SCENES }, (_, s) => s * BEATS_PER_SCENE * BEAT_SEC),
  });
  if (built.dropped.length > 0) {
    console.log(`[§42] planner dropped ${built.dropped.length}:`);
    for (const d of built.dropped.slice(0, 8)) console.log(`[§42]   ${d}`);
  }
  const result = runCinematicPipeline({
    videoId: 42,
    scenes: built.scenes,
    voice: { url: voicePath, durationSec: TOTAL_BEATS * BEAT_SEC },
  });
  const timeline = result.timeline;
  const planSec = (Date.now() - tPlan) / 1000;

  const issues = validateTimeline(timeline).issues;
  const blocking = issues.filter((i) => !NON_BLOCKING_ISSUES.has(i.code));
  const videoCount = timeline.tracks.reduce(
    (n, t) => n + (t.kind === "VIDEO" ? t.clips.length : 0), 0
  );
  console.log(
    `[§42] planned in ${planSec.toFixed(1)}s: ${videoCount} shots, ${timeline.durationSec.toFixed(2)}s, ` +
      `${issues.length} issue(s), ${blocking.length} blocking`
  );
  for (const b of blocking.slice(0, 8)) console.log(`[§42] BLOCKING ${formatTimelineIssue(b)}`);

  const out = path.join(dir, "feature.mp4");
  const tRender = Date.now();
  let rendered;
  try {
    rendered = await renderTimeline({
      timeline,
      workDir: path.join(dir, "render"),
      outputPath: out,
      resolveMedia: async (clip) => {
        const id = clip.source.providerAssetId ?? "";
        const g = Number(id.replace("feat-", ""));
        return Number.isFinite(g) ? media[g % POOL] ?? null : null;
      },
      /**
       * The narration, and NOTHING else.
       *
       * The plan also asks for ambience, which names Freesound recordings by identity. There is no
       * FREESOUND_API_KEY here, so those clips are correctly reported as "no source" — the same
       * thing production does without the key. Generating a file and handing it back under a
       * Freesound id would be a fabricated provider response, and the render would then prove the
       * mix works on material the deployment cannot actually obtain.
       */
      resolveAudio: async (_id, url) => (url === voicePath ? voicePath : null),
    });
  } catch (err) {
    console.log(`[§42] RENDER THREW after ${((Date.now() - tRender) / 1000).toFixed(1)}s`);
    throw err;
  }
  const renderSec = (Date.now() - tRender) / 1000;

  console.log(
    `[§42] rendered in ${renderSec.toFixed(1)}s ` +
      `(${(renderSec / Math.max(1, timeline.durationSec)).toFixed(2)}x realtime)`
  );
  console.log(
    `[§42] executed clips=${rendered.clipsRendered}/${videoCount} ` +
      `cameras=${rendered.camerasExecuted} transitions=${rendered.transitionsRendered} ` +
      `captions=${rendered.captionsDrawn} texts=${rendered.textsDrawn} ` +
      `audioTracks=${rendered.audioTracks} ducked=${rendered.duckedTracks} ` +
      `ffmpegCommands=${rendered.ffmpegCommands} graphics=${rendered.graphicsRenderer}`
  );
  for (const s of rendered.skipped.slice(0, 10)) console.log(`[§42] not carried: ${s}`);
  if (rendered.skipped.length > 10) {
    console.log(`[§42] …and ${rendered.skipped.length - 10} more not carried`);
  }

  const meta = await probe(out);
  const bytes = Number(meta.format?.size ?? 0);
  const dur = Number(meta.format?.duration ?? 0);
  console.log(
    `[§42] file ${(bytes / 1e6).toFixed(1)} MB, ${dur.toFixed(2)}s vs planned ` +
      `${timeline.durationSec.toFixed(2)}s (drift ${(dur - timeline.durationSec).toFixed(3)}s)`
  );
  for (const s of meta.streams ?? []) {
    console.log(
      `[§42] stream ${s.codec_type ?? "?"} ${s.width ?? ""}x${s.height ?? ""} ${s.r_frame_rate ?? ""}`
    );
  }

  const av = await checkFileAvSync(out);
  console.log(
    `[§42] avSync ok=${av.ok} ` +
      (av.findings.length === 0
        ? "no findings"
        : av.findings.map((f) => `${f.code}(${f.detail})`).join(" "))
  );

  console.log(`[§42] wall clock ${((Date.now() - t0) / 1000 / 60).toFixed(2)} min`);
  console.log(`[§42] OUTPUT ${out}`);

  return {
    blocking: blocking.map((b) => b.code),
    blockingDetail: blocking.map(formatTimelineIssue).join("\n"),
    plannedClips: videoCount,
    clipsRendered: rendered.clipsRendered,
    plannedSec: timeline.durationSec,
    fileSec: dur,
    fps: timeline.format.fps,
    avFindings: av.findings.map((f) => `${f.code}: ${f.detail}`),
  };
}

/**
 * A vitest file rather than a plain script for one reason: `videoPipeline` sits in an import cycle
 * that Node's ESM loader will not initialise on its own (`cinematicEffectsEngine` reads a constant
 * from it at module scope), and vitest's loader resolves it the way production's bundler does.
 *
 * It is deliberately OUTSIDE the default `include` (`server/**`), so `npx vitest run` never picks it
 * up. Run it explicitly:
 *
 *     npx vitest run --include "scripts/**\/*.spec.ts"
 *     TARGET_MIN=3 npx vitest run --include "scripts/**\/*.spec.ts"
 */
describe("\u00a742 \u2014 a feature-length render, measured", () => {
  it(`renders ${TARGET_MIN} minutes through the production chain`, async () => {
    const measured = await main();
    /**
     * The assertions are the ones a long render can actually settle. Everything else it produces is
     * a MEASUREMENT reported to the log, because there is no correct value for "how long should a
     * nine-minute render take" that is not a property of this machine.
     */
    expect(measured.blocking, measured.blockingDetail).toEqual([]);
    // Every planned shot reached the file. A long render dropping shots silently is the failure.
    expect(measured.clipsRendered).toBe(measured.plannedClips);
    // The file is as long as the plan said, within a frame.
    const frame = 1 / measured.fps;
    expect(Math.abs(measured.fileSec - measured.plannedSec)).toBeLessThan(2 * frame);
    // And the two streams line up, by the production A/V check.
    expect(measured.avFindings, measured.avFindings.join("; ")).toEqual([]);
  }, 45 * 60_000);
});
